package com.merchtyl.product;

public enum ProductCapability {
    RETAIL,
    FOOD_SERVICE,
    TRACK_INVENTORY,
    ALLOW_DECIMAL_QUANTITY,
    ALLOW_DISCOUNT,
    ALLOW_RETURN,
    ALLOW_REFUND,
    ALLOW_PRICE_OVERRIDE,
    REQUIRE_AGE_VERIFICATION,
    REQUIRE_SERIAL_NUMBER,
    REQUIRE_EXTERNAL_REFERENCE,
    REQUIRE_CUSTOMER,
    SEND_TO_KITCHEN,
    EXCLUDE_FROM_LOYALTY,
    RESTRICT_PAYMENT_METHOD,
    NON_REFUNDABLE
}
