package com.merchtyl.initialinventory;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.merchtyl.catalogue.*;
import com.merchtyl.common.*;
import com.merchtyl.inventory.*;
import com.merchtyl.product.*;
import com.merchtyl.security.*;
import com.merchtyl.store.*;
import com.merchtyl.supplier.*;
import com.merchtyl.tax.*;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.*;
import java.time.*;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;
import static com.merchtyl.initialinventory.InitialInventoryDtos.*;

@Service
public class InitialInventoryService {
    private final InitialInventoryWorkbookService workbooks; private final InitialInventoryImportRepository imports; private final StoreAccessService access;
    private final StoreRepository stores; private final ProductRepository products; private final ProductVariantRepository variants; private final ProductBarcodeRepository barcodes;
    private final StoreProductRepository storeProducts; private final InventoryBalanceRepository balances; private final InventoryTransactionRepository transactions;
    private final CategoryRepository categories; private final BrandRepository brands; private final UnitOfMeasureRepository units; private final TaxCategoryRepository taxes; private final SupplierRepository suppliers; private final ProductSupplierRepository productSuppliers;
    private final ProductReferenceGenerator references; private final SkuGenerator skuGenerator; private final ObjectMapper objectMapper; private final Clock clock=Clock.systemUTC();
    public InitialInventoryService(InitialInventoryWorkbookService workbooks,InitialInventoryImportRepository imports,StoreAccessService access,StoreRepository stores,ProductRepository products,ProductVariantRepository variants,ProductBarcodeRepository barcodes,StoreProductRepository storeProducts,InventoryBalanceRepository balances,InventoryTransactionRepository transactions,CategoryRepository categories,BrandRepository brands,UnitOfMeasureRepository units,TaxCategoryRepository taxes,SupplierRepository suppliers,ProductSupplierRepository productSuppliers,ProductReferenceGenerator references,SkuGenerator skuGenerator,ObjectMapper objectMapper){this.workbooks=workbooks;this.imports=imports;this.access=access;this.stores=stores;this.products=products;this.variants=variants;this.barcodes=barcodes;this.storeProducts=storeProducts;this.balances=balances;this.transactions=transactions;this.categories=categories;this.brands=brands;this.units=units;this.taxes=taxes;this.suppliers=suppliers;this.productSuppliers=productSuppliers;this.references=references;this.skuGenerator=skuGenerator;this.objectMapper=objectMapper;}

    @Transactional(readOnly=true) public byte[] template(UUID storeId,Authentication auth){Context c=context(storeId,auth);return workbooks.template(c.store(),"Merchant");}

    @Transactional
    public ValidationResponse validate(UUID storeId,String filename,byte[] file,Authentication auth){
        Context c=context(storeId,auth); requireNotInitialized(c.tenantId(),storeId);
        if(filename==null||!filename.toLowerCase(Locale.ROOT).endsWith(".xlsx"))throw new BadRequestException("INITIAL_INVENTORY_INVALID_FILE");
        List<RawRow> raw=workbooks.parse(file); InitialInventoryImport job=new InitialInventoryImport(c.tenantId(),storeId,safeFilename(filename),c.actor().getId(),InitialInventoryWorkbookService.TEMPLATE_VERSION,Instant.now(clock));
        List<Product> tenantProducts=products.findAllByTenantId(c.tenantId());List<ProductVariant> tenantVariants=variants.findAllByTenantId(c.tenantId());List<ProductBarcode> tenantBarcodes=barcodes.findAllByTenantId(c.tenantId());
        Map<String,Product> productByReference=tenantProducts.stream().collect(Collectors.toMap(p->p.getProductReference().toLowerCase(Locale.ROOT),Function.identity()));
        Set<String> existingSkus=new HashSet<>();tenantProducts.forEach(p->existingSkus.add(p.getSku().toLowerCase(Locale.ROOT)));Map<String,ProductVariant> variantBySku=tenantVariants.stream().collect(Collectors.toMap(v->v.getSku().toLowerCase(Locale.ROOT),Function.identity()));existingSkus.addAll(variantBySku.keySet());
        Map<String,ProductBarcode> barcodeByCode=tenantBarcodes.stream().collect(Collectors.toMap(b->b.getBarcode().toLowerCase(Locale.ROOT),Function.identity()));
        Map<String,Product> groupResolved=new HashMap<>();Set<String> conflictingGroups=new HashSet<>();for(RawRow row:raw){if(!blank(row.productReference()))continue;Product resolved=null;if(!blank(row.barcode())){ProductBarcode b=barcodeByCode.get(row.barcode().trim().toLowerCase(Locale.ROOT));if(b!=null)resolved=b.getProduct();}if(resolved==null&&!blank(row.sku())){ProductVariant v=variantBySku.get(normalizeSkuKey(row.sku()));if(v!=null)resolved=v.getProduct();}if(resolved!=null){String key=normalizeName(row.productName());Product prior=groupResolved.putIfAbsent(key,resolved);if(prior!=null&&!prior.getId().equals(resolved.getId()))conflictingGroups.add(key);}}
        Set<String> workbookBarcodes=new HashSet<>(),workbookSkus=new HashSet<>(),reservedSkus=new HashSet<>(),rowSignatures=new HashSet<>();
        Map<String,List<RawRow>> newGroups=raw.stream().filter(r->blank(r.productReference())).collect(Collectors.groupingBy(r->normalizeName(r.productName()),LinkedHashMap::new,Collectors.toList()));
        Set<Integer> inconsistent=new HashSet<>();for(List<RawRow> group:newGroups.values())if(!consistent(group))group.forEach(r->inconsistent.add(r.rowNumber()));
        for(RawRow row:raw){List<String> errors=new ArrayList<>();validateRequired(row,errors);if(inconsistent.contains(row.rowNumber())||conflictingGroups.contains(normalizeName(row.productName())))errors.add("INCONSISTENT_PRODUCT_ATTRIBUTES");String signature=List.of(String.valueOf(row.productReference()),String.valueOf(row.productName()),String.valueOf(row.variantName()),String.valueOf(row.barcode()),String.valueOf(row.sku()),String.valueOf(row.sellingPrice()),String.valueOf(row.openingQuantity())).stream().map(String::trim).map(String::toLowerCase).collect(Collectors.joining("|"));if(!rowSignatures.add(signature))errors.add("DUPLICATE_VARIANT_ROW");
            String barcode=clean(row.barcode());String requestedSku=clean(row.sku());List<String> rowBarcodes=barcodeAliases(row,errors);for(String candidate:rowBarcodes)if(!workbookBarcodes.add(candidate.toLowerCase(Locale.ROOT)))errors.add("DUPLICATE_BARCODE");
            ProductBarcode existingBarcode=barcode==null?null:barcodeByCode.get(barcode.toLowerCase(Locale.ROOT));
            String sku=null;try{sku=requestedSku==null&&existingBarcode!=null&&existingBarcode.getVariant()!=null?existingBarcode.getVariant().getSku():requestedSku==null?skuGenerator.unique(row.productName(),row.variantName(),candidate->reservedSkus.contains(candidate)||existingSkus.contains(candidate.toLowerCase(Locale.ROOT))):skuGenerator.normalizeProvided(requestedSku);}catch(RuntimeException e){errors.add("INVALID_SKU");sku="INVALID";}
            if(!workbookSkus.add(sku.toLowerCase(Locale.ROOT)))errors.add("DUPLICATE_SKU");reservedSkus.add(sku);
            Product byReference=blank(row.productReference())?null:productByReference.get(row.productReference().trim().toLowerCase(Locale.ROOT));
            if(!blank(row.productReference())&&byReference==null)errors.add("UNKNOWN_PRODUCT_REFERENCE");if(byReference!=null&&!byReference.getName().equalsIgnoreCase(clean(row.productName())))errors.add("PRODUCT_REFERENCE_NAME_MISMATCH");
            ProductBarcode byBarcode=existingBarcode;ProductVariant bySku=sku.equals("INVALID")?null:variantBySku.get(sku.toLowerCase(Locale.ROOT));if(bySku==null&&existingSkus.contains(sku.toLowerCase(Locale.ROOT)))errors.add("DUPLICATE_SKU");
            if(byBarcode!=null&&byBarcode.getVariant()==null)errors.add("EXISTING_VARIANT_PRODUCT_MISMATCH");
            if(byBarcode!=null&&bySku!=null&&byBarcode.getVariant()!=null&&!byBarcode.getVariant().getId().equals(bySku.getId()))errors.add("BARCODE_SKU_VARIANT_CONFLICT");
            Product resolved=byReference!=null?byReference:byBarcode!=null?byBarcode.getProduct():bySku!=null?bySku.getProduct():groupResolved.get(normalizeName(row.productName()));
            if(byReference!=null&&((byBarcode!=null&&!byBarcode.getProduct().getId().equals(byReference.getId()))||(bySku!=null&&!bySku.getProduct().getId().equals(byReference.getId()))))errors.add("VARIANT_PRODUCT_REFERENCE_CONFLICT");
            if(resolved!=null&&!resolved.getName().equalsIgnoreCase(clean(row.productName())))errors.add("EXISTING_VARIANT_PRODUCT_MISMATCH");
            ProductVariant resolvedVariant=byBarcode!=null?byBarcode.getVariant():bySku;
            for(String candidate:rowBarcodes){ProductBarcode owned=barcodeByCode.get(candidate.toLowerCase(Locale.ROOT));if(owned!=null&&resolvedVariant!=null&&(owned.getVariant()==null||!owned.getVariant().getId().equals(resolvedVariant.getId())))errors.add("BARCODE_SKU_VARIANT_CONFLICT");}
            if(resolved!=null&&!existingAttributesMatch(resolved,row))errors.add("INCONSISTENT_PRODUCT_ATTRIBUTES");
            if(resolvedVariant!=null&&!resolvedVariant.getName().equalsIgnoreCase(clean(row.variantName())))errors.add("EXISTING_VARIANT_PRODUCT_MISMATCH");
            if(resolvedVariant!=null&&resolvedVariant.getPrice().compareTo(zero(row.sellingPrice()))!=0)errors.add("EXISTING_VARIANT_PRICE_MISMATCH");
            validateReferences(row,c.tenantId(),errors);
            job.addRow(new InitialInventoryImportRow(row.rowNumber(),resolved==null?clean(row.productReference()):resolved.getProductReference(),requiredOrEmpty(row.productName()),requiredOrEmpty(row.variantName()),barcode,String.join(";",rowBarcodes.stream().filter(candidate->!candidate.equals(barcode)).toList()),sku,zero(row.sellingPrice()),zero(row.costPrice()),zero(row.openingQuantity()),row.lowStockLevel(),clean(row.category()),clean(row.brand()),clean(row.unitCode()),requiredOrEmpty(row.taxCategory()),clean(row.supplier()),Boolean.TRUE.equals(row.ageRestricted()),row.active()==null||row.active(),resolved==null?"CREATE_PRODUCT":"REUSE_PRODUCT",resolvedVariant==null?"CREATE_VARIANT":"REUSE_VARIANT",resolved==null?null:resolved.getId(),resolvedVariant==null?null:resolvedVariant.getId(),errors));
        }
        int errors=(int)job.getRows().stream().filter(r->!r.errors().isEmpty()).count();int groups=(int)job.getRows().stream().map(r->r.getProductId()!=null?"id:"+r.getProductId():"new:"+normalizeName(r.getProductName())).distinct().count();job.summarize(groups,job.getRows().size()-errors,errors);imports.save(job);return response(job);
    }

    @Transactional
    public ImportResult confirm(UUID storeId,UUID importId,Authentication auth){
        Context c=context(storeId,auth);stores.findByIdAndTenantIdForUpdate(storeId,c.tenantId()).orElseThrow(()->new NotFoundException("Store not found"));
        InitialInventoryImport job=imports.findWithRowsById(importId).filter(i->i.getTenantId().equals(c.tenantId())&&i.getStoreId().equals(storeId)).orElseThrow(()->new NotFoundException("INITIAL_INVENTORY_IMPORT_NOT_FOUND"));
        if(job.getStatus()==InitialInventoryImportStatus.COMPLETED){try{return objectMapper.readValue(job.getResultJson(),ImportResult.class);}catch(Exception e){throw new ConflictException("INITIAL_INVENTORY_ALREADY_COMPLETED");}}
        if(Instant.now(clock).isAfter(job.getExpiresAt())){job.expire();throw new ConflictException("INITIAL_INVENTORY_IMPORT_EXPIRED");}
        if(job.getErrorRows()>0)throw new BadRequestException("INITIAL_INVENTORY_VALIDATION_FAILED");requireNotInitialized(c.tenantId(),storeId);job.processing(Instant.now(clock));
        int pc=0,pr=0,vc=0,vr=0,sa=0,oi=0;Map<String,Product> newProducts=new HashMap<>();Set<UUID> countedReused=new HashSet<>(),suppliersAttached=new HashSet<>();
        for(InitialInventoryImportRow row:job.getRows()){
            Product product=row.getProductId()==null?newProducts.get(normalizeName(row.getProductName())):products.findByIdAndTenantId(row.getProductId(),c.tenantId()).orElseThrow(()->new ConflictException("INITIAL_INVENTORY_STATE_CHANGED"));
            if(product==null){product=createProduct(c.tenantId(),row);newProducts.put(normalizeName(row.getProductName()),product);pc++;}else if(row.getProductId()!=null&&countedReused.add(product.getId()))pr++;
            ProductVariant variant=null;if(row.getVariantId()!=null){variant=variants.findById(row.getVariantId()).orElseThrow(()->new ConflictException("INITIAL_INVENTORY_STATE_CHANGED"));if(!variant.getProduct().getId().equals(product.getId()))throw new ConflictException("INITIAL_INVENTORY_STATE_CHANGED");}
            if(variant==null){if(variants.existsByTenantIdAndSkuIgnoreCase(c.tenantId(),row.getSku()))throw new ConflictException("SKU_ALREADY_EXISTS");variant=product.addVariant(new ProductVariantValues(row.getSku(),row.getVariantName(),null,row.getCostPrice(),row.getSellingPrice(),row.isActive()));vc++;}else{if(variant.getPrice().compareTo(row.getSellingPrice())!=0)throw new ConflictException("EXISTING_VARIANT_PRICE_MISMATCH");vr++;}
            ProductVariant targetVariant=variant;for(String code:persistedBarcodeAliases(row)){if(barcodes.existsByTenantIdAndBarcodeIgnoreCase(c.tenantId(),code)){ProductBarcode existing=barcodes.findByTenantIdAndBarcodeIgnoreCase(c.tenantId(),code).orElseThrow();if(existing.getVariant()==null||!existing.getVariant().getId().equals(targetVariant.getId()))throw new ConflictException("BARCODE_ALREADY_ASSIGNED");continue;}product.addBarcode(targetVariant,new ProductBarcodeValues(code,row.getSku(),product.getBarcodes().stream().noneMatch(b->b.getVariant()!=null&&b.getVariant().getId().equals(targetVariant.getId())),true));}products.saveAndFlush(product);
            if(product.getAvailabilityScope()==ProductAvailabilityScope.SELECTED_STORES&&storeProducts.findByTenantIdAndStore_IdAndProduct_Id(c.tenantId(),storeId,product.getId()).isEmpty()){StoreProduct mapping=new StoreProduct(c.tenantId(),c.store(),product);mapping.update(new StoreProductRequest(storeId,true,true,product.getPrice(),product.getCost(),null,row.getLowStockLevel(),true,true));storeProducts.save(mapping);sa++;}
            if(suppliersAttached.add(product.getId()))attachSupplier(product,row.getSupplier());
            Optional<InventoryBalance> existing=balances.findByStoreIdAndProductIdAndVariantId(storeId,product.getId(),variant.getId());if(existing.isPresent()&&existing.get().getQuantityOnHand().compareTo(BigDecimal.ZERO)!=0)throw new ConflictException("STORE_INVENTORY_ALREADY_INITIALIZED");
            InventoryBalance balance=existing.orElse(null);if(balance==null)balance=new InventoryBalance(c.store(),product,variant,BigDecimal.ZERO.setScale(4),Instant.now(clock));if(row.getOpeningQuantity().compareTo(BigDecimal.ZERO)>0){balance.apply(row.getOpeningQuantity(),Instant.now(clock));balances.saveAndFlush(balance);transactions.save(new InventoryTransaction(balance,InventoryTransactionType.OPENING_STOCK,row.getOpeningQuantity(),balance.getQuantityOnHand(),"INITIAL_INVENTORY_SETUP",job.getId(),"Initial inventory setup",c.actor().getId(),Instant.now(clock)));oi++;}else balances.save(balance);
        }
        ImportResult result=new ImportResult(job.getId(),storeId,pc,pr,vc,vr,sa,oi);try{job.complete(objectMapper.writeValueAsString(result),Instant.now(clock));}catch(Exception e){throw new IllegalStateException(e);}return result;
    }

    private Product createProduct(UUID tenantId,InitialInventoryImportRow row){Category category=find(categories,row.getCategory());Brand brand=find(brands,row.getBrand());UnitOfMeasure unit=find(units,row.getUnitCode());TaxCategory tax=findTax(tenantId,row.getTaxCategory());String productSku=skuGenerator.unique(row.getProductName(),"P",candidate->products.existsByTenantIdAndSkuIgnoreCase(tenantId,candidate)||variants.existsByTenantIdAndSkuIgnoreCase(tenantId,candidate));Product p=new Product(new ProductValues(productSku,row.getProductName(),null,SellableType.STANDARD_PRODUCT,unit,row.getCostPrice(),row.getSellingPrice(),category,brand,row.isActive(),true,false,null,tax.getId(),List.of(),List.of(),row.isAgeRestricted()?Set.of(ProductCapability.TRACK_INVENTORY,ProductCapability.REQUIRE_AGE_VERIFICATION):Set.of(ProductCapability.TRACK_INVENTORY)));p.assignTenant(tenantId);p.assignProductReference(references.next(tenantId));p.setAvailabilityScope(ProductAvailabilityScope.SELECTED_STORES);if(row.isAgeRestricted())p.setMinimumAge(18);try{return products.saveAndFlush(p);}catch(DataIntegrityViolationException e){throw new ConflictException("INITIAL_INVENTORY_CONCURRENT_CONFLICT");}}
    private void attachSupplier(Product product,String value){Supplier supplier=find(suppliers,value);if(supplier!=null&&!productSuppliers.existsByProductIdAndSupplierId(product.getId(),supplier.getId()))productSuppliers.save(new ProductSupplier(new ProductSupplierValues(product,supplier,null,true,true)));}
    private Context context(UUID storeId,Authentication auth){UUID tenantId=access.currentTenantId(auth);User actor=access.requireProductManagementScope(auth,Set.of(storeId));Store store=access.tenantStore(tenantId,storeId);return new Context(tenantId,store,actor);}
    private void requireNotInitialized(UUID tenantId,UUID storeId){if(transactions.existsByStoreId(storeId)||imports.existsByTenantIdAndStoreIdAndStatus(tenantId,storeId,InitialInventoryImportStatus.COMPLETED))throw new ConflictException("STORE_INVENTORY_ALREADY_INITIALIZED");}
    private ValidationResponse response(InitialInventoryImport job){return new ValidationResponse(job.getId(),job.getStoreId(),job.getTotalRows(),job.getProductCount(),job.getValidRows(),job.getWarningRows(),job.getErrorRows(),job.getErrorRows()==0,job.getRows().stream().map(RowPreview::from).toList());}
    private void validateRequired(RawRow r,List<String> e){if(blank(r.productName())||blank(r.variantName()))e.add("REQUIRED_FIELD_MISSING");if(r.sellingPrice()==null||r.sellingPrice().signum()<0||scale(r.sellingPrice())>4)e.add("INVALID_PRICE");if(r.costPrice()!=null&&(r.costPrice().signum()<0||scale(r.costPrice())>4))e.add("INVALID_PRICE");if(r.openingQuantity()==null||r.openingQuantity().signum()<0||scale(r.openingQuantity())>4)e.add("INVALID_OPENING_QUANTITY");if(r.lowStockLevel()!=null&&(r.lowStockLevel().signum()<0||scale(r.lowStockLevel())>4))e.add("INVALID_OPENING_QUANTITY");if(r.ageRestricted()==null||r.active()==null)e.add("INVALID_BOOLEAN");}
    private void validateReferences(RawRow r,UUID tenantId,List<String> e){if(!blank(r.category())&&find(categories,r.category())==null)e.add("UNKNOWN_CATEGORY");if(!blank(r.brand())&&find(brands,r.brand())==null)e.add("UNKNOWN_BRAND");if(!blank(r.unitCode())&&find(units,r.unitCode())==null)e.add("UNKNOWN_UNIT");if(blank(r.taxCategory())||findTax(tenantId,r.taxCategory())==null)e.add("TAX_CATEGORY_NOT_FOUND");if(!blank(r.supplier())&&find(suppliers,r.supplier())==null)e.add("UNKNOWN_SUPPLIER");}
    private boolean consistent(List<RawRow> rows){if(rows.isEmpty())return true;RawRow a=rows.get(0);return rows.stream().allMatch(r->Objects.equals(normalizeName(a.category()),normalizeName(r.category()))&&Objects.equals(normalizeName(a.brand()),normalizeName(r.brand()))&&Objects.equals(normalizeName(a.unitCode()),normalizeName(r.unitCode()))&&Objects.equals(normalizeName(a.taxCategory()),normalizeName(r.taxCategory()))&&Objects.equals(normalizeName(a.supplier()),normalizeName(r.supplier()))&&Objects.equals(a.lowStockLevel(),r.lowStockLevel())&&Objects.equals(a.ageRestricted(),r.ageRestricted())&&Objects.equals(a.active(),r.active()));}
    private boolean existingAttributesMatch(Product p,RawRow r){return matches(r.category(),p.getCategory()==null?null:p.getCategory().getName(),p.getCategory()==null?null:p.getCategory().getCode())&&matches(r.brand(),p.getBrand()==null?null:p.getBrand().getName(),p.getBrand()==null?null:p.getBrand().getCode())&&matches(r.unitCode(),p.getUnitOfMeasure()==null?null:p.getUnitOfMeasure().getName(),p.getUnitOfMeasure()==null?null:p.getUnitOfMeasure().getCode())&&matches(r.taxCategory(),p.getTaxCategoryId()==null?null:taxes.findById(p.getTaxCategoryId()).map(TaxCategory::getName).orElse(null),p.getTaxCategoryId()==null?null:taxes.findById(p.getTaxCategoryId()).map(TaxCategory::getCode).orElse(null));}
    private static List<String> barcodeAliases(RawRow row,List<String> errors){List<String> values=new ArrayList<>();if(!blank(row.barcode()))values.add(row.barcode());if(!blank(row.additionalBarcodes()))values.addAll(Arrays.asList(row.additionalBarcodes().split(";",-1)));List<String> result=new ArrayList<>();Set<String> keys=new HashSet<>();for(String value:values){try{String normalized=BarcodeNormalizer.normalize(value);if(!keys.add(normalized.toLowerCase(Locale.ROOT)))errors.add("DUPLICATE_BARCODE");else result.add(normalized);}catch(BadRequestException exception){errors.add(exception.getMessage());}}return result;}
    private static List<String> persistedBarcodeAliases(InitialInventoryImportRow row){List<String> values=new ArrayList<>();if(!blank(row.getBarcode()))values.add(row.getBarcode());if(!blank(row.getAdditionalBarcodes()))values.addAll(Arrays.asList(row.getAdditionalBarcodes().split(";")));return values;}
    private static boolean matches(String supplied,String name,String code){return blank(supplied)||(name!=null&&name.equalsIgnoreCase(supplied.trim()))||(code!=null&&code.equalsIgnoreCase(supplied.trim()));}
    private static <T> T find(org.springframework.data.jpa.repository.JpaRepository<T,UUID> repo,String value){if(blank(value))return null;String wanted=value.trim();return repo.findAll().stream().filter(v->{if(v instanceof CatalogueReference c)return c.isActive()&&(c.getCode().equalsIgnoreCase(wanted)||c.getName().equalsIgnoreCase(wanted));if(v instanceof TaxCategory t)return t.isActive()&&(t.getCode().equalsIgnoreCase(wanted)||t.getName().equalsIgnoreCase(wanted));if(v instanceof Supplier s)return s.isActive()&&(s.getCode().equalsIgnoreCase(wanted)||s.getName().equalsIgnoreCase(wanted));return false;}).findFirst().orElse(null);}
    private TaxCategory findTax(UUID tenantId,String value){if(blank(value))return null;String wanted=value.trim();return taxes.findAll().stream().filter(TaxCategory::isActive).filter(t->t.getTenantId()==null||t.getTenantId().equals(tenantId)).filter(t->t.getCode().equalsIgnoreCase(wanted)||t.getName().equalsIgnoreCase(wanted)).findFirst().orElse(null);}
    private static int scale(BigDecimal v){return Math.max(0,v.stripTrailingZeros().scale());} private static BigDecimal zero(BigDecimal v){return v==null?BigDecimal.ZERO.setScale(4):v.setScale(4,RoundingMode.HALF_UP);} private static boolean blank(String v){return v==null||v.isBlank();} private static String clean(String v){return blank(v)?null:v.trim();} private static String requiredOrEmpty(String v){return v==null?"":v.trim();} private static String normalizeName(String v){return v==null?"":v.trim().toLowerCase(Locale.ROOT);} private static String normalizeSkuKey(String v){return v==null?"":v.trim().toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9-]","").toLowerCase(Locale.ROOT);} private static String safeFilename(String v){String clean=v.replaceAll("[\\r\\n\\t]","_");return clean.substring(0,Math.min(255,clean.length()));}
    private record Context(UUID tenantId,Store store,User actor){}
}
