package com.merchtyl.inventoryimport;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.merchtyl.common.ConflictException;
import com.merchtyl.inventory.*;
import com.merchtyl.product.*;
import com.merchtyl.security.*;
import com.merchtyl.store.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.security.core.Authentication;
import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class InventoryUpdateImportWorkflowTest {
 @Test void validationReportsBothColumnsAndPerformsNoInventoryWrite() throws Exception {Fixture f=new Fixture();var result=f.service.validate(f.storeId,"inventory.xlsx",workbook(f.storeId,f.variantId,3,10d,4d),f.auth);assertThat(result.canConfirm()).isFalse();assertThat(result.errorRows()).isEqualTo(1);assertThat(result.unchangedRows()).isZero();assertThat(result.rows().get(0).errors()).contains("Enter either Counted Stock or Add Stock, not both.");verifyNoInteractions(f.inventory);verify(f.balances,never()).save(any());}
 @Test void confirmationRechecksLockedBalanceAndWritesAuthoritativeLedgerDelta() throws Exception {Fixture f=new Fixture();var validation=f.service.validate(f.storeId,"inventory.xlsx",workbook(f.storeId,f.variantId,3,null,10d),f.auth);InventoryImportBatch batch=f.saved.getValue();when(f.batches.findByIdForUpdate(validation.importId())).thenReturn(Optional.of(batch));InventoryBalance locked=mock(InventoryBalance.class);when(locked.getQuantityOnHand()).thenReturn(new BigDecimal("5"));when(locked.getVersion()).thenReturn(7L);when(f.balances.findVariantForUpdate(f.storeId,f.variantId)).thenReturn(Optional.of(locked));when(f.inventory.recordStockChange(any(),eq(f.auth))).thenReturn(new InventoryTransactionResponse(UUID.randomUUID(),UUID.randomUUID(),f.storeId,f.productId,InventoryTransactionType.PURCHASE,new BigDecimal("10"),new BigDecimal("15"),"INVENTORY_IMPORT",validation.importId(),"received",f.actorId,Instant.now(),Instant.now(),0,f.variantId));var result=f.service.confirm(f.storeId,validation.importId(),f.auth);ArgumentCaptor<InventoryStockChangeRequest> request=ArgumentCaptor.forClass(InventoryStockChangeRequest.class);verify(f.inventory).recordStockChange(request.capture(),eq(f.auth));assertThat(request.getValue().quantityDelta()).isEqualByComparingTo("10");assertThat(request.getValue().balanceVersion()).isEqualTo(7);assertThat(result.rows().get(0).currentStock()).isEqualByComparingTo("5");assertThat(result.rows().get(0).finalStock()).isEqualByComparingTo("15");verify(f.batches).findByIdForUpdate(validation.importId());}
 @Test void countedStockAlreadyAtTargetIsReportedUnchanged() throws Exception {Fixture f=new Fixture();InventoryBalance current=mock(InventoryBalance.class);when(current.getVariant()).thenReturn(f.variant);when(current.getQuantityOnHand()).thenReturn(new BigDecimal("10"));when(f.balances.findAllByStoreIdAndVariantIdIn(eq(f.storeId),anyList())).thenReturn(List.of(current));var result=f.service.validate(f.storeId,"inventory.xlsx",workbook(f.storeId,f.variantId,3,10d,null),f.auth);assertThat(result.changedRows()).isZero();assertThat(result.unchangedRows()).isEqualTo(1);assertThat(result.rows().get(0).adjustment()).isEqualByComparingTo("0");}
 @Test void completedBatchCannotBeConfirmedTwice() throws Exception {Fixture f=new Fixture();f.service.validate(f.storeId,"inventory.xlsx",workbook(f.storeId,f.variantId,3,null,10d),f.auth);InventoryImportBatch batch=f.saved.getValue();batch.confirm(f.actorId,1,Instant.now());when(f.batches.findByIdForUpdate(batch.getId())).thenReturn(Optional.of(batch));assertThatThrownBy(()->f.service.confirm(f.storeId,batch.getId(),f.auth)).isInstanceOf(ConflictException.class).hasMessage("INVENTORY_IMPORT_ALREADY_COMPLETED");verifyNoInteractions(f.inventory);}
 private static byte[] workbook(UUID store,UUID variant,double downloaded,Double counted,Double add)throws Exception{try(var wb=new XSSFWorkbook();var out=new ByteArrayOutputStream()){var sheet=wb.createSheet("Inventory Update");String[] headers={"Product Code","Product Name","Variant","SKU","Barcode","Current Stock","Counted Stock (Set To)","Add Stock (Received Qty)","Variant ID"};var h=sheet.createRow(0);for(int i=0;i<headers.length;i++)h.createCell(i).setCellValue(headers[i]);var row=sheet.createRow(1);row.createCell(5).setCellValue(downloaded);if(counted!=null)row.createCell(6).setCellValue(counted);if(add!=null)row.createCell(7).setCellValue(add);row.createCell(8).setCellValue(variant.toString());var meta=wb.createSheet("_Merchtyl Metadata");meta.createRow(0).createCell(1).setCellValue(1);meta.createRow(1).createCell(1).setCellValue(store.toString());wb.write(out);return out.toByteArray();}}
 private static class Fixture {final UUID tenantId=UUID.randomUUID(),storeId=UUID.randomUUID(),actorId=UUID.randomUUID(),productId=UUID.randomUUID(),variantId=UUID.randomUUID();final InventoryImportBatchRepository batches=mock(InventoryImportBatchRepository.class);final StoreAccessService access=mock(StoreAccessService.class);final StoreRepository stores=mock(StoreRepository.class);final ProductVariantRepository variants=mock(ProductVariantRepository.class);final StoreProductRepository storeProducts=mock(StoreProductRepository.class);final InventoryBalanceRepository balances=mock(InventoryBalanceRepository.class);final InventoryService inventory=mock(InventoryService.class);final Authentication auth=mock(Authentication.class);final User actor=mock(User.class);final Store store=mock(Store.class);final Product product=mock(Product.class);final ProductVariant variant=mock(ProductVariant.class);final ArgumentCaptor<InventoryImportBatch> saved=ArgumentCaptor.forClass(InventoryImportBatch.class);final InventoryUpdateImportService service;
  Fixture(){when(actor.getTenantId()).thenReturn(tenantId);when(actor.getId()).thenReturn(actorId);when(access.currentTenantUser(auth)).thenReturn(actor);when(access.requireProductManagementScope(auth,Set.of(storeId))).thenReturn(actor);when(stores.findById(storeId)).thenReturn(Optional.of(store));when(store.getTenantId()).thenReturn(tenantId);when(variant.getId()).thenReturn(variantId);when(variant.getTenantId()).thenReturn(tenantId);when(variant.isActive()).thenReturn(true);when(variant.getProduct()).thenReturn(product);when(variant.getName()).thenReturn("Regular");when(variant.getSku()).thenReturn("SKU");when(product.getId()).thenReturn(productId);when(product.getTenantId()).thenReturn(tenantId);when(product.isActive()).thenReturn(true);when(product.isInventoryTrackingEnabled()).thenReturn(true);when(product.getAvailabilityScope()).thenReturn(ProductAvailabilityScope.ALL_STORES);when(product.getName()).thenReturn("Coffee");when(product.getProductReference()).thenReturn("P1");when(product.getBarcodes()).thenReturn(List.of());when(variants.findAllById(any())).thenReturn(List.of(variant));when(storeProducts.findByTenantIdAndStore_IdAndActiveTrueAndSellableTrue(tenantId,storeId)).thenReturn(List.of());when(balances.findAllByStoreIdAndVariantIdIn(eq(storeId),anyList())).thenReturn(List.of());when(batches.saveAndFlush(saved.capture())).thenAnswer(i->i.getArgument(0));service=new InventoryUpdateImportService(new InventoryUpdateWorkbookService(),batches,access,stores,variants,storeProducts,balances,inventory,new ObjectMapper(),Clock.fixed(Instant.parse("2026-09-22T12:00:00Z"),ZoneOffset.UTC));}}
}
