spring:
  datasource:
    url: jdbc:postgresql://ep-holy-forest-au795cxk-pooler.c-10.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_Ji0gpIVLs9Yb

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.merchtyl: DEBUG
    org.flywaydb: INFO
    org.hibernate.SQL: DEBUG

merchtyl:
  jwt:
    issuer: merchtyl-local
    secret: MERCHTYL_IS_THE_BEST_POS_SYSTEM_IN_THE_WORLD
  security:
    cors:
      allowed-origins: http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080
  testing:
    user-provisioning:
      enabled: true
      key: merchtyl-local-test-key
      default-user-password: Test1234!
  email:
    provider: resend
    from-address: support@merchtyl.com
    frontend-base-url: http://localhost:5173
    resend:
      enabled: true
      api-key: re_bsVQkPbD_FqqwBYXpHMdQ9k4GSVdLJwM8

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
