ALTER TABLE merchant_profiles ALTER COLUMN industry_type TYPE VARCHAR(40);

UPDATE merchant_profiles
SET industry_type = CASE upper(trim(coalesce(industry_type, '')))
    WHEN 'CONVENIENCE STORE' THEN 'CONVENIENCE_STORE'
    WHEN 'CONVENIENCE_STORE' THEN 'CONVENIENCE_STORE'
    WHEN 'GROCERY STORE' THEN 'GROCERY_STORE'
    WHEN 'GROCERY_STORE' THEN 'GROCERY_STORE'
    WHEN 'RESTAURANT' THEN 'RESTAURANT'
    WHEN 'CAFE' THEN 'CAFE'
    WHEN 'CAFE / COFFEE SHOP' THEN 'CAFE'
    WHEN 'FAST FOOD / TAKEOUT' THEN 'FAST_FOOD'
    WHEN 'FAST_FOOD' THEN 'FAST_FOOD'
    WHEN 'RETAIL' THEN 'RETAIL'
    WHEN 'RETAIL STORE' THEN 'RETAIL'
    WHEN 'PHARMACY' THEN 'PHARMACY'
    WHEN 'GAS STATION / CONVENIENCE' THEN 'GAS_STATION'
    WHEN 'GAS_STATION' THEN 'GAS_STATION'
    WHEN 'LIQUOR STORE' THEN 'LIQUOR_STORE'
    WHEN 'LIQUOR_STORE' THEN 'LIQUOR_STORE'
    WHEN 'BAKERY' THEN 'BAKERY'
    WHEN 'SPECIALTY FOOD STORE' THEN 'SPECIALTY_FOOD'
    WHEN 'SPECIALTY_FOOD' THEN 'SPECIALTY_FOOD'
    WHEN 'GENERAL MERCHANDISE' THEN 'GENERAL_MERCHANDISE'
    WHEN 'GENERAL_MERCHANDISE' THEN 'GENERAL_MERCHANDISE'
    WHEN 'OTHER' THEN 'OTHER'
    ELSE 'OTHER'
END;

ALTER TABLE merchant_profiles ALTER COLUMN industry_type SET NOT NULL;
ALTER TABLE merchant_profiles ADD CONSTRAINT ck_merchant_profiles_industry_type CHECK (industry_type IN (
    'CONVENIENCE_STORE','GROCERY_STORE','RESTAURANT','CAFE','FAST_FOOD','RETAIL','PHARMACY',
    'GAS_STATION','LIQUOR_STORE','BAKERY','SPECIALTY_FOOD','GENERAL_MERCHANDISE','OTHER'
));
