package com.merchtyl.email;

public enum EmailTemplateCode {
    MERCHANT_OWNER_ACTIVATION,
    MERCHANT_OWNER_INVITATION_RESEND,
    MERCHANT_OWNER_TEMPORARY_CREDENTIALS,
    MERCHANT_OWNER_TEMPORARY_CREDENTIALS_RESEND,
    PASSWORD_RESET,
    PLATFORM_ADMIN_INVITATION,
    MERCHANT_SUSPENDED,
    MERCHANT_REACTIVATED,
    MERCHANT_SUBSCRIPTION_INVOICE,
    TEST_EMAIL
}
