package com.merchtyl.cash;

public enum CashLedgerSourceType {
    SESSION_OPENING_FLOAT,
    SALE_CASH_RECEIPT,
    SALE_CHANGE_GIVEN,
    LOTTERY_SALE_CASH,
    LOTTERY_PAYOUT_CASH,
    LOTTERY_PAYOUT_REVERSAL,
    LOTTERY_SALE_CANCELLATION_CASH,
    CASH_REFUND,
    CASH_MOVEMENT,
    SESSION_CLOSE_ADJUSTMENT
}
