package com.merchtyl.sales;

import java.math.BigDecimal;
import java.util.UUID;
import com.merchtyl.product.DepositType;

public record SaleItemResponse(
        UUID id,
        SaleLineType lineType,
        UUID productId,
        UUID variantId,
        int lineNumber,
        String productSku,
        String productName,
        String variantSku,
        String variantName,
        CustomItemTaxTreatment customItemTaxTreatment,
        BigDecimal quantity,
        BigDecimal unitPrice,
        BigDecimal discountAmount,
        UUID promotionId,
        String promotionName,
        SaleAdjustmentType promotionType,
        Integer promotionBuyQuantity,
        BigDecimal promotionBundlePrice,
        BigDecimal promotionRegularAmount,
        BigDecimal promotionDiscountAmount,
        BigDecimal promotionFinalAmount,
        BigDecimal completedProductCost,
        BigDecimal completedProductPrice,
        String completedProductCapabilities,
        boolean priceOverride,
        boolean ageVerified,
        String serialNumber,
        String externalReference,
        UUID customerId,
        String paymentMethodCode,
        BigDecimal lineSubtotal,
        BigDecimal estimatedTaxAmount,
        BigDecimal lineTotal,
        UUID foodMenuItemId,
        UUID foodMenuItemVariantId,
        String foodMenuItemName,
        String foodMenuItemVariantName,
        java.util.List<String> foodMenuModifiers,
        java.util.List<FoodComponentSnapshot> foodMenuComponents,
        DepositType depositType,
        BigDecimal depositUnitAmount,
        BigDecimal depositQuantity,
        BigDecimal depositTotal,
        long version
) {
    public SaleItemResponse(UUID id, UUID productId, int lineNumber, String productSku, String productName,
                            BigDecimal quantity, BigDecimal unitPrice, BigDecimal discountAmount,
                            BigDecimal completedProductCost, BigDecimal completedProductPrice,
                            String completedProductCapabilities, boolean priceOverride, boolean ageVerified,
                            String serialNumber, String externalReference, UUID customerId, String paymentMethodCode,
                            BigDecimal lineSubtotal, BigDecimal estimatedTaxAmount, BigDecimal lineTotal, long version) {
        this(id, SaleLineType.CATALOG_PRODUCT, productId, null, lineNumber, productSku, productName, null, null, null, quantity, unitPrice,
                discountAmount, null,null,null,null,null,null,null,null, completedProductCost, completedProductPrice, completedProductCapabilities,
                priceOverride, ageVerified, serialNumber, externalReference, customerId, paymentMethodCode,
                lineSubtotal, estimatedTaxAmount, lineTotal, null, null, null, null, java.util.List.of(), java.util.List.of(),
                null, null, BigDecimal.ZERO, BigDecimal.ZERO, version);
    }

    static SaleItemResponse from(SaleItem item) {
        return new SaleItemResponse(
                item.getId(),
                item.getLineType(),
                item.getProduct() == null ? null : item.getProduct().getId(),
                item.getVariant() == null ? null : item.getVariant().getId(),
                item.getLineNumber(),
                item.getProductSku(),
                item.getProductName(),
                item.getVariantSku(),
                item.getVariantName(),
                item.getCustomItemTaxTreatment(),
                item.getQuantity(),
                item.getUnitPrice(),
                item.getDiscountAmount(),
                item.getPromotionId(),item.getPromotionName(),item.getPromotionType(),item.getPromotionBuyQuantity(),item.getPromotionBundlePrice(),
                item.getPromotionRegularAmount(),item.getPromotionDiscountAmount(),item.getPromotionFinalAmount(),
                item.getCompletedProductCost(),
                item.getCompletedProductPrice(),
                item.getCompletedProductCapabilities(),
                item.isPriceOverride(),
                item.isAgeVerified(),
                item.getSerialNumber(),
                item.getExternalReference(),
                item.getCustomerId(),
                item.getPaymentMethodCode(),
                item.getLineSubtotal(),
                item.getEstimatedTaxAmount(),
                item.getLineTotal(),
                item.getMenuItemId(),
                item.getMenuItemVariantId(),
                item.getItemNameSnapshot(),
                item.getMenuVariantNameSnapshot(),
                item.getMenuModifiers(),
                item.getMenuComponents(),
                item.getDepositType(),
                item.getDepositUnitAmount(),
                item.getDepositQuantity(),
                item.getDepositTotal(),
                item.getVersion());
    }
}
