package com.merchtyl.sales;

public enum SaleAdjustmentType {
    SET_UNIT_PRICE,
    DISCOUNT_AMOUNT,
    DISCOUNT_PERCENTAGE,
    MATCH_ADVERTISED_PRICE,
    MATCH_SHELF_PRICE,
    DAMAGED_ITEM_DISCOUNT,
    MANAGER_OVERRIDE,
    PROMOTIONAL_CORRECTION,
    OTHER,
    QUANTITY_CORRECTION,
    ITEM_REMOVAL,
    SALE_DISCOUNT,
    PAYMENT_CORRECTION
}
