package com.merchtyl.eod;

public enum EndOfDayExceptionType {
    PRICE_OVERRIDES,
    MANUAL_DISCOUNTS,
    VOIDED_TRANSACTIONS,
    REFUNDS,
    FORCE_CLOSED_SESSIONS,
    CASH_VARIANCES,
    NEGATIVE_STOCK_SALES,
    FAILED_PAYMENT_ATTEMPTS,
    DUPLICATE_IDEMPOTENCY_ATTEMPTS,
    PERMISSION_DENIED_EVENTS,
    LOTTERY_REFERRALS,
    LOTTERY_REVERSALS,
    MANUAL_CASH_CORRECTIONS,
    REOPENED_BUSINESS_DAY
}
