package com.merchtyl.eod;

import com.lowagie.text.*;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfPageEventHelper;
import com.lowagie.text.pdf.PdfTemplate;
import com.lowagie.text.pdf.PdfWriter;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.math.BigDecimal;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** Branded, paginated rendering of an immutable EOD snapshot. */
final class EndOfDayPdfRenderer {
    private static final Color NAVY = new Color(19, 49, 82);
    private static final Color BLUE = new Color(30, 103, 174);
    private static final Color LIGHT = new Color(239, 244, 249);
    private static final Color RULE = new Color(205, 215, 225);
    private static final Font BODY = new Font(Font.HELVETICA, 9, Font.NORMAL, Color.DARK_GRAY);
    private static final Font SMALL = new Font(Font.HELVETICA, 8, Font.NORMAL, Color.GRAY);
    private static final Font LABEL = new Font(Font.HELVETICA, 8, Font.BOLD, NAVY);
    private static final Font VALUE = new Font(Font.HELVETICA, 15, Font.BOLD, NAVY);

    private EndOfDayPdfRenderer() {}

    static byte[] render(EndOfDayReportResponse report, String timezone) {
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        Document document = new Document(PageSize.LETTER, 42, 42, 46, 44);
        try {
            PdfWriter writer = PdfWriter.getInstance(document, output);
            writer.setPageEvent(new Footer(report.reportNumber()));
            document.open();
            renderHeader(document, report, timezone);
            renderManagementSummary(document, report);
            document.newPage();
            renderOperationalDetails(document, report, timezone);
            document.close();
            return output.toByteArray();
        } catch (DocumentException exception) {
            throw new IllegalStateException("Unable to render EOD PDF", exception);
        }
    }

    private static void renderHeader(Document document, EndOfDayReportResponse report, String timezone) throws DocumentException {
        PdfPTable header = new PdfPTable(new float[]{1, 1});
        header.setWidthPercentage(100);
        header.addCell(logoCell());
        header.addCell(cell("END OF DAY REPORT", new Font(Font.HELVETICA, 13, Font.BOLD, NAVY), Element.ALIGN_RIGHT, false));
        document.add(header);
        document.add(rule());

        PdfPTable meta = new PdfPTable(new float[]{1, 1});
        meta.setWidthPercentage(100);
        meta.setSpacingBefore(7);
        addMeta(meta, report.storeName(), "Store: " + report.storeCode());
        addMeta(meta, formatDate(report), "Business Date");
        addMeta(meta, report.reportNumber(), "Report · Revision " + report.revision());
        addMeta(meta, formatTime(report.generatedAt(), timezone), "Generated by " + report.generatedByName());
        document.add(meta);
    }

    private static void renderManagementSummary(Document document, EndOfDayReportResponse report) throws DocumentException {
        sectionTitle(document, "SALES SUMMARY");
        PdfPTable cards = new PdfPTable(4);
        cards.setWidthPercentage(100);
        cards.setSpacingAfter(7);
        kpi(cards, "TOTAL SALES", report.totalSales(), report.currencyCode());
        kpi(cards, "SALES BEFORE TAX", report.totalSalesBeforeTax(), report.currencyCode());
        kpi(cards, "TOTAL TAX", report.totalTaxCollected(), report.currencyCode());
        kpi(cards, "CASH RETAINED IN TILLS", report.cashRetainedInTills(), report.currencyCode());
        document.add(cards);
        financialRows(document, List.of(
                moneyRow("Taxable Sales", report.taxableSales()), moneyRow("Non-Taxable Sales", report.nonTaxableSales()),
                moneyRow("Refunds", report.refundTotal())), report.currencyCode());

        sectionTitle(document, "CASH RECONCILIATION");
        financialRows(document, List.of(
                moneyRow("Initial Opening Cash", report.initialOpeningCash()),
                moneyRow("Cash Received", registerTotal(report, row -> row.cashReceipts().add(row.lotteryCashSales()))),
                moneyRow("Cash Paid In", registerTotal(report, row -> row.cashIn().add(row.floatAdditions()))),
                moneyRow("Cash Payouts", registerTotal(report, EndOfDayRegisterSummaryResponse::payouts).negate()),
                moneyRow("Payout Reversals", registerTotal(report, EndOfDayRegisterSummaryResponse::payoutReversals)),
                moneyRow("Safe Drops", registerTotal(report, EndOfDayRegisterSummaryResponse::safeDrops).negate()),
                moneyRow("Other Cash Out", registerTotal(report, row -> row.cashOut().add(row.expenses()).add(row.floatRemovals())).negate()),
                moneyRow("Cash Before Final Settlement", report.cashBeforeFinalSettlement()),
                moneyRow("Till Sweeps / Cash Removed", report.cashRemovedFromTills().negate()),
                moneyRow("Cash Retained in Tills", report.cashRetainedInTills()),
                moneyRow("Final Counted Cash", report.countedCash()), moneyRow(varianceLabel(report.cashVariance()), report.cashVariance())), report.currencyCode());

        sectionTitle(document, "TAX SUMMARY");
        financialRows(document, List.of(moneyRow("General Tax", tax(report, "GENERAL_TAX")), moneyRow("Vape Tax", tax(report, "VAPE_TAX")),
                moneyRow("Other Tax", tax(report, "OTHER_TAX")), moneyRow("Total Tax", report.totalTaxCollected())), report.currencyCode());

        sectionTitle(document, "PAYMENTS");
        List<MoneyRow> payments = new ArrayList<>();
        for (String method : List.of("CASH", "DEBIT", "CREDIT", "GIFT_CARD")) payments.add(moneyRow(title(method), payment(report, method)));
        payments.add(moneyRow("Other", otherPayments(report)));
        payments.add(moneyRow("Net Payments", report.payments().stream().map(EndOfDayPaymentSummaryResponse::net).reduce(BigDecimal.ZERO, BigDecimal::add)));
        financialRows(document, payments, report.currencyCode());

        sectionTitle(document, "LOTTERY");
        if (report.lottery() == null) noActivity(document); else financialRows(document, List.of(
                moneyRow("Lottery Sold", report.lottery().lotterySales()), moneyRow("Lottery Payouts", report.lottery().lotteryPayouts()),
                moneyRow("Net Lottery", report.lottery().netLottery())), report.currencyCode());
        sectionTitle(document, "DEPOSITS");
        financialRows(document, List.of(moneyRow("Collected", report.depositsCollected()), moneyRow("Payouts", report.depositPayouts()), moneyRow("Net", report.netDeposits())), report.currencyCode());
    }

    private static void renderOperationalDetails(Document document, EndOfDayReportResponse report, String timezone) throws DocumentException {
        sectionTitle(document, "REGISTER RECONCILIATION");
        table(document, List.of("Register", "Sessions", "Initial", "Target", "Removed", "Retained", "Variance"),
                report.registerReconciliation().stream().map(row -> List.of(row.registerCode(), String.valueOf(row.sessionCount()),
                        money(row.initialFloat(), report.currencyCode()), money(row.targetFloat(), report.currencyCode()), money(row.cashRemoved(), report.currencyCode()),
                        money(row.cashRetained(), report.currencyCode()), money(row.variance(), report.currencyCode()))).toList());
        sectionTitle(document, "REGISTER SESSION DETAIL");
        table(document, List.of("Register / Cashier", "Opened", "Closed", "Opening", "Expected", "Counted", "Variance", "Removed", "Left"),
                report.registers().stream().map(row -> List.of(
                        row.registerCode() + " / " + row.openedByName(), formatTime(row.openedAt(), timezone),
                        row.closedAt() == null ? "Open" : formatTime(row.closedAt(), timezone),
                        money(row.openingFloat(), report.currencyCode()), money(row.expectedCash(), report.currencyCode()),
                        money(row.countedCash(), report.currencyCode()), money(row.variance(), report.currencyCode()),
                        money(row.sessionCashRemoved(), report.currencyCode()), money(row.sessionCashRetained(), report.currencyCode()))).toList());
        sectionTitle(document, "SALES DETAILS");
        financialRows(document, List.of(moneyRow("Gross Merchandise Sales", report.grossSales()), moneyRow("Discounts", report.discountTotal().negate()),
                moneyRow("Refunds", report.refundTotal().negate()), moneyRow("Sales Before Tax", report.totalSalesBeforeTax())), report.currencyCode());
        sectionTitle(document, "CASHIER SUMMARY");
        table(document, List.of("Cashier", "Transactions", "Net Sales", "Cash Handled"), report.cashiers().stream().map(row -> List.of(row.cashierName(), String.valueOf(row.transactionCount()), money(row.netSales(), report.currencyCode()), money(row.cashHandled(), report.currencyCode()))).toList());
        sectionTitle(document, "CATEGORY SALES BY TAX TREATMENT");
        table(document, List.of("Category", "Tax Treatment", "Qty", "Sales Before Tax", "Tax"), report.categorySalesDistribution().stream()
                .filter(row -> row.netSales().abs().compareTo(new BigDecimal("0.005")) >= 0)
                .map(row -> List.of(row.categoryName(), row.taxTreatmentLabel(), row.quantitySold().stripTrailingZeros().toPlainString(),
                        money(row.netSales(), report.currencyCode()), money(row.taxCollected(), report.currencyCode()))).toList());
        sectionTitle(document, "INVENTORY");
        if (report.inventory() == null) noActivity(document); else financialRows(document, List.of(moneyRow("Units Deducted", report.inventory().deductedBySales()), moneyRow("Units Restored", report.inventory().restoredByReturns()), moneyRow("Value Movement", report.inventory().inventoryValueMovement())), report.currencyCode());
        sectionTitle(document, "EXCEPTIONS");
        if (report.exceptions().isEmpty()) paragraph(document, "No exceptions recorded."); else table(document, List.of("Type", "Count", "Amount", "Details"), report.exceptions().stream().map(row -> List.of(title(row.exceptionType().name()), String.valueOf(row.count()), money(row.totalAmount(), report.currencyCode()), row.details() == null ? "" : row.details())).toList());
        List<List<String>> varianceRows = report.registers().stream()
                .filter(row -> row.variance().compareTo(BigDecimal.ZERO) != 0 || row.forceClosed())
                .map(row -> List.of(row.registerCode() + " / " + row.openedByName(),
                        money(row.variance(), report.currencyCode()), row.forceClosed() ? "Yes" : "No",
                        blankAsNone(row.forceCloseReason()), blankAsNone(row.varianceExplanation())))
                .toList();
        if (!varianceRows.isEmpty()) {
            table(document, List.of("Register / Cashier", "Variance", "Force Closed", "Force-close reason", "Variance explanation"), varianceRows);
        }
        sectionTitle(document, "CLOSED / SIGNED BY");
        if (report.signOff() != null) financialTextRows(document, List.of(
                List.of("Name", report.signOff().managerName()), List.of("Date / Time", formatTime(report.signOff().signedAt(), timezone)),
                List.of("Cash Variance", money(report.cashVariance(), report.currencyCode())),
                List.of("Variance Explanation", blankAsNone(report.signOff().varianceExplanation()))));
    }

    private static void sectionTitle(Document document, String title) throws DocumentException {
        Paragraph p = new Paragraph(title, new Font(Font.HELVETICA, 10, Font.BOLD, NAVY));
        p.setSpacingBefore(10); p.setSpacingAfter(4); p.setKeepTogether(true); document.add(p); document.add(rule());
    }
    private static void kpi(PdfPTable table, String label, BigDecimal value, String currency) {
        PdfPCell c = new PdfPCell(); c.setBackgroundColor(LIGHT); c.setBorderColor(Color.WHITE); c.setPadding(8);
        c.addElement(new Paragraph(label, LABEL)); c.addElement(new Paragraph(money(value, currency), VALUE)); table.addCell(c);
    }
    private static void financialRows(Document document, List<MoneyRow> rows, String currency) throws DocumentException {
        financialTextRows(document, rows.stream().map(row -> List.of(row.label(), money(row.value(), currency))).toList());
    }
    private static void financialTextRows(Document document, List<List<String>> rows) throws DocumentException {
        PdfPTable table = new PdfPTable(new float[]{3, 1}); table.setWidthPercentage(100);
        for (List<String> row : rows) { table.addCell(cell(row.get(0), BODY, Element.ALIGN_LEFT, true)); table.addCell(cell(row.get(1), BODY, Element.ALIGN_RIGHT, true)); }
        document.add(table);
    }
    private static void table(Document document, List<String> headers, List<List<String>> rows) throws DocumentException {
        if (rows.isEmpty()) { noActivity(document); return; }
        PdfPTable table = new PdfPTable(headers.size()); table.setWidthPercentage(100); table.setHeaderRows(1); table.setSplitRows(true);
        headers.forEach(value -> { PdfPCell c = cell(value, LABEL, Element.ALIGN_LEFT, true); c.setBackgroundColor(LIGHT); table.addCell(c); });
        rows.forEach(row -> row.forEach(value -> table.addCell(cell(value, BODY, Element.ALIGN_LEFT, true)))); document.add(table);
    }
    private static PdfPCell cell(String text, Font font, int alignment, boolean border) { PdfPCell c = new PdfPCell(new Phrase(text == null ? "" : text, font)); c.setHorizontalAlignment(alignment); c.setPadding(5); c.setBorder(border ? Rectangle.BOTTOM : Rectangle.NO_BORDER); c.setBorderColor(RULE); return c; }
    private static PdfPCell logoCell() {
        PdfPCell cell = new PdfPCell(); cell.setBorder(Rectangle.NO_BORDER); cell.setPadding(0);
        try (InputStream stream = EndOfDayPdfRenderer.class.getResourceAsStream("/branding/merchtyl-logo-horizontal.png")) {
            if (stream != null) {
                Image logo = Image.getInstance(stream.readAllBytes()); logo.scaleToFit(125, 30); cell.addElement(logo); return cell;
            }
        } catch (Exception ignored) {
            // Keep exports available if a downstream packaging process omits the optional image.
        }
        cell.addElement(new Paragraph("MERCHTYL", new Font(Font.HELVETICA, 19, Font.BOLD, BLUE)));
        return cell;
    }
    private static PdfPTable rule() { PdfPTable table = new PdfPTable(1); table.setWidthPercentage(100); PdfPCell c = new PdfPCell(new Phrase(" ")); c.setFixedHeight(2); c.setBorder(Rectangle.BOTTOM); c.setBorderColor(RULE); table.addCell(c); return table; }
    private static void addMeta(PdfPTable table, String main, String sub) { PdfPCell c = cell(main, new Font(Font.HELVETICA, 10, Font.BOLD, NAVY), Element.ALIGN_LEFT, false); c.addElement(new Paragraph(sub, SMALL)); table.addCell(c); }
    private static void noActivity(Document document) throws DocumentException { paragraph(document, "No activity"); }
    private static void paragraph(Document document, String text) throws DocumentException { Paragraph p = new Paragraph(text, SMALL); p.setSpacingAfter(4); document.add(p); }
    private static MoneyRow moneyRow(String label, BigDecimal value) { return new MoneyRow(label, value == null ? BigDecimal.ZERO : value); }
    private static String money(BigDecimal value, String currency) {
        NumberFormat format = NumberFormat.getCurrencyInstance(Locale.CANADA);
        format.setCurrency(java.util.Currency.getInstance(currency));
        format.setMinimumFractionDigits(2);
        format.setMaximumFractionDigits(2);
        return format.format(value == null ? BigDecimal.ZERO : value);
    }
    private static String formatDate(EndOfDayReportResponse report) { return report.businessDate().format(DateTimeFormatter.ofPattern("MMMM d, uuuu", Locale.CANADA)); }
    private static String formatTime(java.time.Instant time, String timezone) { ZoneId zone; try { zone = ZoneId.of(timezone); } catch (Exception ignored) { zone = ZoneId.of("UTC"); } return DateTimeFormatter.ofPattern("MMM d, uuuu · h:mm a", Locale.CANADA).withZone(zone).format(time); }
    private static BigDecimal tax(EndOfDayReportResponse report, String code) { return report.taxes().stream().filter(row -> code.equals(row.componentCode())).map(EndOfDayTaxSummaryResponse::netTaxCollected).reduce(BigDecimal.ZERO, BigDecimal::add); }
    private static BigDecimal payment(EndOfDayReportResponse report, String method) { return report.payments().stream().filter(row -> method.equals(row.paymentMethod().name())).map(EndOfDayPaymentSummaryResponse::net).reduce(BigDecimal.ZERO, BigDecimal::add); }
    private static BigDecimal otherPayments(EndOfDayReportResponse report) { return report.payments().stream().filter(row -> !List.of("CASH", "DEBIT", "CREDIT", "GIFT_CARD").contains(row.paymentMethod().name())).map(EndOfDayPaymentSummaryResponse::net).reduce(BigDecimal.ZERO, BigDecimal::add); }
    private static BigDecimal registerTotal(EndOfDayReportResponse report, java.util.function.Function<EndOfDayRegisterSummaryResponse, BigDecimal> selector) { return report.registers().stream().map(selector).reduce(BigDecimal.ZERO.setScale(2), BigDecimal::add); }
    private static String varianceLabel(BigDecimal value) { return value.signum() < 0 ? "Variance — Short" : value.signum() > 0 ? "Variance — Over" : "Variance — Balanced"; }
    private static String title(String value) { String lower = value.replace('_', ' ').toLowerCase(Locale.CANADA); return Character.toUpperCase(lower.charAt(0)) + lower.substring(1); }
    private static String blankAsNone(String value) { return value == null || value.isBlank() ? "None" : value; }
    private record MoneyRow(String label, BigDecimal value) {}

    private static final class Footer extends PdfPageEventHelper {
        private final String reportNumber;
        private PdfTemplate totalPages;
        private Footer(String reportNumber) { this.reportNumber = reportNumber; }
        @Override public void onOpenDocument(PdfWriter writer, Document document) { totalPages = writer.getDirectContent().createTemplate(24, 10); }
        @Override public void onEndPage(PdfWriter writer, Document document) {
            try {
                BaseFont font = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.WINANSI, false);
                String left = "Merchtyl  ·  Confidential Business Report  ·  " + reportNumber;
                com.lowagie.text.pdf.PdfContentByte canvas = writer.getDirectContent();
                canvas.setColorStroke(RULE); canvas.moveTo(42, 34); canvas.lineTo(570, 34); canvas.stroke();
                canvas.beginText(); canvas.setFontAndSize(font, 8); canvas.setColorFill(Color.GRAY); canvas.setTextMatrix(42, 22); canvas.showText(left);
                String page = "Page " + writer.getPageNumber() + " of "; float x = 550 - font.getWidthPoint(page, 8); canvas.setTextMatrix(x, 22); canvas.showText(page); canvas.endText();
                canvas.addTemplate(totalPages, 552, 22);
            } catch (Exception exception) { throw new IllegalStateException(exception); }
        }
        @Override public void onCloseDocument(PdfWriter writer, Document document) {
            try {
                BaseFont font = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.WINANSI, false);
                totalPages.beginText(); totalPages.setFontAndSize(font, 8); totalPages.setColorFill(Color.GRAY);
                totalPages.setTextMatrix(0, 0); totalPages.showText(String.valueOf(writer.getPageNumber() - 1)); totalPages.endText();
            } catch (Exception exception) { throw new IllegalStateException(exception); }
        }
    }
}
