import { QueryClient,QueryClientProvider } from '@tanstack/react-query';import { ThemeProvider } from '@mui/material';import { render,screen,waitFor } from '@testing-library/react';import userEvent from '@testing-library/user-event';import { MemoryRouter } from 'react-router-dom';import { InitialInventorySetupPage } from './InitialInventorySetupPage';import { theme } from '../../app/theme';

const api=vi.hoisted(()=>({stores:vi.fn(),download:vi.fn(),validate:vi.fn(),confirm:vi.fn()}));
vi.mock('../../api/client',()=>({listStores:api.stores,downloadInitialInventoryTemplate:api.download,validateInitialInventory:api.validate,confirmInitialInventory:api.confirm}));
vi.mock('../../app/session',()=>({useSession:()=>({session:{roles:['OWNER']},currentUser:{roles:['OWNER'],permissions:['INVENTORY_MANAGE','PRODUCT_CREATE']},getValidAccessToken:async()=> 'token'})}));
function setup(){return render(<ThemeProvider theme={theme}><QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}><MemoryRouter><InitialInventorySetupPage/></MemoryRouter></QueryClientProvider></ThemeProvider>)}
const store={id:'store-1',name:'Downtown',code:'DOWN',active:true};
beforeEach(()=>{vi.clearAllMocks();api.stores.mockResolvedValue({content:[store]});Object.defineProperty(URL,'createObjectURL',{configurable:true,value:vi.fn(()=> 'blob:test')});Object.defineProperty(URL,'revokeObjectURL',{configurable:true,value:vi.fn()});});

it('downloads, validates, previews, confirms and shows completion actions',async()=>{
 api.download.mockResolvedValue(new Blob(['xlsx']));api.validate.mockResolvedValue({importId:'import-1',storeId:'store-1',totalVariantRows:1,productGroups:1,validRows:1,warningRows:0,errorRows:0,canImport:true,rows:[{rowNumber:2,productReference:null,productName:'Coca Cola',variantName:'500 ml',barcode:'00123',sku:'COC500ML',sellingPrice:2.79,openingQuantity:18,actions:['CREATE_PRODUCT','CREATE_VARIANT','ASSIGN_PRODUCT_TO_STORE','CREATE_OPENING_INVENTORY'],errors:[]}]});api.confirm.mockResolvedValue({importId:'import-1',storeId:'store-1',productsCreated:1,productsReused:0,variantsCreated:1,variantsReused:0,storeAssignments:1,openingInventory:1});setup();
 await userEvent.click(await screen.findByLabelText('Store'));await userEvent.click(screen.getByRole('option',{name:'Downtown (DOWN)'}));await userEvent.click(screen.getByRole('button',{name:'Download Excel Template'}));
 const input=document.querySelector('input[type="file"]') as HTMLInputElement;await userEvent.upload(input,new File(['xlsx'],'opening.xlsx',{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));await userEvent.click(screen.getByRole('button',{name:'Validate Inventory'}));
 expect(await screen.findByText('Initial Inventory Preview')).toBeInTheDocument();expect(screen.getByText('COC500ML')).toBeInTheDocument();expect(screen.getByText('Generated on import')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Confirm Import'}));expect(await screen.findByRole('heading',{name:'Initial Inventory Setup Complete'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'View Inventory'})).toHaveAttribute('href','/inventory');
});

it('disables confirm when validation has hard row errors',async()=>{api.validate.mockResolvedValue({importId:'bad',storeId:'store-1',totalVariantRows:1,productGroups:1,validRows:0,warningRows:0,errorRows:1,canImport:false,rows:[{rowNumber:2,productReference:null,productName:'Coca Cola',variantName:'500 ml',barcode:'B1',sku:'COC500ML',sellingPrice:2.79,openingQuantity:18,actions:['CREATE_PRODUCT','CREATE_VARIANT'],errors:['UNKNOWN_TAX_CATEGORY']}]});setup();await userEvent.click(await screen.findByLabelText('Store'));await userEvent.click(screen.getByRole('option',{name:'Downtown (DOWN)'}));await userEvent.upload(document.querySelector('input[type="file"]') as HTMLInputElement,new File(['xlsx'],'bad.xlsx'));await userEvent.click(screen.getByRole('button',{name:'Validate Inventory'}));expect(await screen.findByText('Row 2: Unknown Tax Category')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Confirm Import'})).toBeDisabled();expect(api.confirm).not.toHaveBeenCalled();});
