import AddIcon from '@mui/icons-material/Add';
import { Alert, Box, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, Grid, MenuItem, Stack, Switch, TextField, Typography } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import * as React from 'react';
import { createFoodMenuCategory, createFoodMenuChoiceGroup, createFoodMenuItem, deleteFoodMenuCategory, deleteFoodMenuItem, listFoodMenuCategories, listFoodMenuChoiceGroups, listFoodMenuItems, listProducts, listStores, updateFoodMenuCategory, updateFoodMenuChoiceGroup, updateFoodMenuItem, updateFoodMenuItemAvailability } from '../../api/client';
import type { FoodMenuChoiceGroup, FoodMenuItem } from '../../api/types';
import { useSession } from '../../app/session';

const emptyItem = { productId: '', categoryId: '', displayName: '', description: '', price: 0, displayOrder: 0, available: true, imageUrl: '', variants: [] as Array<{clientId:string;name:string;price:number;displayOrder:number;available:boolean}>, modifierGroupAssignments: [] as Array<{modifierGroupId:string;minimumSelections:number;maximumSelections:number;displayOrder:number;active:boolean}>, components: [] as Array<{clientId:string;name:string;includedByDefault:boolean;removable:boolean;allowExtra:boolean;extraPrice:number;displayOrder:number;active:boolean}> };

export function FoodMenuPage() {
  const { currentUser, getValidAccessToken } = useSession();
  const queryClient = useQueryClient();
  const stores = useQuery({ queryKey: ['stores', 'restaurant-menu'], queryFn: async () => listStores(await getValidAccessToken(), { size: 100 }) });
  const eligible = (stores.data?.content ?? []).filter((store) => store.capabilities?.includes('FOOD_SERVICE'));
  const [storeId, setStoreId] = React.useState('');
  const selected = storeId || eligible[0]?.id || '';
  const categories = useQuery({ queryKey: ['food-menu-categories', selected], queryFn: async () => listFoodMenuCategories(await getValidAccessToken(), selected), enabled: Boolean(selected) });
  const items = useQuery({ queryKey: ['food-menu-items', selected], queryFn: async () => listFoodMenuItems(await getValidAccessToken(), selected), enabled: Boolean(selected) });
  const choiceGroups = useQuery({ queryKey: ['food-menu-choice-groups', selected], queryFn: async () => listFoodMenuChoiceGroups(await getValidAccessToken(), selected), enabled: Boolean(selected) });
  const products = useQuery({ queryKey: ['products', 'restaurant-menu', selected], queryFn: async () => listProducts(await getValidAccessToken(), { storeId: selected, active: true, size: 200 }), enabled: Boolean(selected) });
  const [categoryOpen, setCategoryOpen] = React.useState(false);
  const [itemOpen, setItemOpen] = React.useState(false);
  const [editingItemId, setEditingItemId] = React.useState<string | null>(null);
  const [itemSaved, setItemSaved] = React.useState(false);
  const [choiceOpen,setChoiceOpen]=React.useState(false);
  const [editingChoice,setEditingChoice]=React.useState<FoodMenuChoiceGroup|null>(null);
  const [attachCreatedChoice,setAttachCreatedChoice]=React.useState(false);
  const [linkProduct, setLinkProduct] = React.useState(false);
  const [category, setCategory] = React.useState({ name: '', displayOrder: 0, active: true, imageUrl: '' });
  const [item, setItem] = React.useState(emptyItem);
  const canManage = currentUser?.permissions?.some((permission) => permission === 'PRODUCT_MANAGE' || permission === 'FOOD_ORDER_UPDATE');
  const refresh = () => {
    void queryClient.invalidateQueries({ queryKey: ['food-menu-categories', selected] });
    void queryClient.invalidateQueries({ queryKey: ['food-menu-items', selected] });
    void queryClient.invalidateQueries({ queryKey: ['food-menu-choice-groups', selected] });
  };
  const addCategory = useMutation({ mutationFn: async () => createFoodMenuCategory(await getValidAccessToken(), selected, category), onSuccess: () => { setCategoryOpen(false); setCategory({ name: '', displayOrder: 0, active: true, imageUrl: '' }); refresh(); } });
  const itemPayload = () => ({ ...item, productId: linkProduct ? item.productId : undefined, variants:item.variants.map(({clientId:_,...value})=>value), components:item.components.map(({clientId:_,...value})=>value) });
  const saveItem = useMutation({ mutationFn: async () => editingItemId ? updateFoodMenuItem(await getValidAccessToken(), selected, editingItemId, itemPayload()) : createFoodMenuItem(await getValidAccessToken(), selected, itemPayload()), onSuccess: () => { setItemOpen(false); setEditingItemId(null); setItem(emptyItem); setLinkProduct(false); setItemSaved(true); refresh(); } });
  const availability = useMutation({ mutationFn: async (value: { id: string; available: boolean }) => updateFoodMenuItemAvailability(await getValidAccessToken(), selected, value.id, value.available), onSuccess: refresh });
  const changeCategory = useMutation({ mutationFn: async (value: { id: string; name: string; displayOrder: number; active: boolean; imageUrl?: string }) => updateFoodMenuCategory(await getValidAccessToken(), selected, value.id, value), onSuccess: refresh });
  const moveItem = useMutation({ mutationFn: async (value: FoodMenuItem) => updateFoodMenuItem(await getValidAccessToken(), selected, value.id, { productId: value.productId ?? undefined, categoryId: value.categoryId, displayName: value.displayName, description: value.description ?? undefined, price: value.price, displayOrder: value.displayOrder, available: value.available, imageUrl: value.imageUrl ?? undefined, variants:value.variants??[], modifierGroupAssignments:(value.modifierGroups??[]).map(group=>({modifierGroupId:group.id,minimumSelections:group.minimumSelections,maximumSelections:group.maximumSelections,displayOrder:group.displayOrder,active:group.active})),components:value.components??[] }), onSuccess: refresh });
  const removeCategory = useMutation({ mutationFn: async (id: string) => deleteFoodMenuCategory(await getValidAccessToken(), selected, id), onSuccess: refresh });
  const removeItem = useMutation({ mutationFn: async (id: string) => deleteFoodMenuItem(await getValidAccessToken(), selected, id), onSuccess: refresh });
  const openCreateItem = () => { setEditingItemId(null); setItem(emptyItem); setLinkProduct(false); setItemSaved(false); setItemOpen(true); };
  const openEditItem = (value: FoodMenuItem) => {
    setEditingItemId(value.id);
    setLinkProduct(!value.madeToOrder);
    setItem({
      productId:value.productId??'', categoryId:value.categoryId, displayName:value.displayName,
      description:value.description??'', price:value.price, displayOrder:value.displayOrder,
      available:value.available, imageUrl:value.imageUrl??'',
      variants:(value.variants??[]).map(variant=>({clientId:variant.id,...variant})),
      modifierGroupAssignments:(value.modifierGroups??[]).map(group=>({modifierGroupId:group.id,minimumSelections:group.minimumSelections,maximumSelections:group.maximumSelections,displayOrder:group.displayOrder,active:group.active})),
      components:(value.components??[]).map(component=>({clientId:component.id,...component}))
    });
    setItemSaved(false);
    setItemOpen(true);
  };

  if (stores.isSuccess && !eligible.length) return <Alert severity="info">No FOOD_SERVICE-enabled stores are available.</Alert>;
  return <Stack spacing={3} sx={{ minWidth: 0 }}>
    <Box><Typography variant="h4">Restaurant Menu</Typography><Typography color="text.secondary">Made-to-order items are separate from Retail Products and Inventory.</Typography></Box>
    <TextField select label="Store" value={selected} onChange={(event) => setStoreId(event.target.value)} sx={{ maxWidth: 420 }}>{eligible.map((store) => <MenuItem key={store.id} value={store.id}>{store.name}</MenuItem>)}</TextField>
    <Stack direction="row" spacing={1} useFlexGap flexWrap="wrap"><Button startIcon={<AddIcon />} variant="contained" disabled={!selected || !canManage} onClick={() => setCategoryOpen(true)}>Add Category</Button><Button startIcon={<AddIcon />} variant="contained" disabled={!selected || !categories.data?.length || !canManage} onClick={openCreateItem}>Add Menu Item</Button><Button startIcon={<AddIcon/>} disabled={!selected||!canManage} onClick={()=>{setAttachCreatedChoice(false);setEditingChoice(null);setChoiceOpen(true);}}>New Choice Group</Button></Stack>
    {itemSaved ? <Alert severity="success" onClose={()=>setItemSaved(false)}>Restaurant menu item saved.</Alert> : null}
    {choiceGroups.data?.length?<Card variant="outlined"><CardContent><Stack spacing={1}><Typography variant="h5">Choice Groups</Typography>{choiceGroups.data.map(group=><Stack key={group.id} direction="row" alignItems="center" spacing={1}><Box sx={{flex:1}}><Typography fontWeight={700}>{group.name}{!group.active?' · Inactive':''}</Typography><Typography variant="caption" color="text.secondary">{group.options.length} choices · Used by {group.usageCount} items</Typography></Box><Button disabled={!canManage} onClick={()=>{setEditingChoice(group);setChoiceOpen(true);}}>Edit</Button></Stack>)}</Stack></CardContent></Card>:null}
    {categories.isSuccess && !categories.data.length ? <Alert severity="info" action={canManage ? <Button onClick={() => setCategoryOpen(true)}>Create Restaurant Menu</Button> : undefined}>No restaurant menu has been created for this store yet.</Alert> : null}
    {(categories.data ?? []).map((group) => <Box key={group.id} sx={{ minWidth: 0 }}>
      <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1} sx={{ mb: 1 }}><Typography variant="h5" sx={{ flex: 1 }}>{group.name} <Typography component="span" color="text.secondary">#{group.displayOrder}{group.active ? '' : ' · Inactive'}</Typography></Typography><Stack direction="row" useFlexGap flexWrap="wrap"><Button size="small" disabled={!canManage} onClick={() => changeCategory.mutate({ ...group, displayOrder: Math.max(0, group.displayOrder - 1), imageUrl: group.imageUrl ?? undefined })}>Move Up</Button><Button size="small" disabled={!canManage} onClick={() => changeCategory.mutate({ ...group, displayOrder: group.displayOrder + 1, imageUrl: group.imageUrl ?? undefined })}>Move Down</Button><Button size="small" disabled={!canManage} onClick={() => changeCategory.mutate({ ...group, active: !group.active, imageUrl: group.imageUrl ?? undefined })}>{group.active ? 'Deactivate' : 'Activate'}</Button><Button size="small" color="error" disabled={!canManage} onClick={() => removeCategory.mutate(group.id)}>Delete</Button></Stack></Stack>
      <Grid container spacing={2}>{(items.data ?? []).filter((value) => value.categoryId === group.id).map((value) => <Grid item xs={12} sm={6} md={4} key={value.id}><Card variant="outlined"><CardContent><Stack spacing={1}><Typography variant="h6">{value.displayName}</Typography>{value.description ? <Typography variant="body2">{value.description}</Typography> : null}<Typography>${Number(value.price).toFixed(2)} · position {value.displayOrder}</Typography><Typography variant="caption">{value.madeToOrder ? 'Made to Order · No inventory tracking' : `Linked Product: ${value.productName}`}</Typography><FormControlLabel control={<Switch checked={value.available} disabled={!canManage || availability.isPending} onChange={(_, checked) => availability.mutate({ id: value.id, available: checked })} />} label={value.available ? 'Available' : 'Sold Out'} /><Stack direction="row" useFlexGap flexWrap="wrap"><Button size="small" disabled={!canManage} onClick={() => openEditItem(value)}>Edit</Button><Button size="small" disabled={!canManage} onClick={() => moveItem.mutate({ ...value, displayOrder: Math.max(0, value.displayOrder - 1) })}>Move Up</Button><Button size="small" disabled={!canManage} onClick={() => moveItem.mutate({ ...value, displayOrder: value.displayOrder + 1 })}>Move Down</Button><Button size="small" color="error" disabled={!canManage} onClick={() => removeItem.mutate(value.id)}>Remove</Button></Stack></Stack></CardContent></Card></Grid>)}</Grid>
    </Box>)}
    <Dialog open={categoryOpen} onClose={() => setCategoryOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Create Restaurant Menu Category</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Name" value={category.name} onChange={(event) => setCategory({ ...category, name: event.target.value })} /><TextField label="Display Order" type="number" value={category.displayOrder} onChange={(event) => setCategory({ ...category, displayOrder: Number(event.target.value) })} /></Stack></DialogContent><DialogActions><Button onClick={() => setCategoryOpen(false)}>Cancel</Button><Button onClick={() => addCategory.mutate()} disabled={!category.name.trim()}>Add</Button></DialogActions></Dialog>
    <Dialog open={itemOpen} onClose={() => !saveItem.isPending && setItemOpen(false)} fullWidth maxWidth="md">
      <DialogTitle>{editingItemId ? 'Edit Food Item' : 'Add Restaurant Menu Item'}</DialogTitle>
      <DialogContent><Stack spacing={2} sx={{ pt: 1 }}>
        {saveItem.isError ? <Alert severity="error">{saveItem.error instanceof Error ? saveItem.error.message : 'Unable to save this menu item.'}</Alert> : null}
        <Typography fontWeight={800}>Basic information</Typography>
        <FormControlLabel control={<Switch checked={!linkProduct} disabled={Boolean(editingItemId)} onChange={(_, madeToOrder) => setLinkProduct(!madeToOrder)} />} label="Made to Order / No Inventory Tracking" />
        {linkProduct ? <TextField select label="Link Existing Product" disabled={Boolean(editingItemId)} value={item.productId} onChange={(event) => { const product = products.data?.content.find((candidate) => candidate.id === event.target.value); setItem({ ...item, productId: event.target.value, displayName: product?.name ?? '', price: product?.price ?? 0 }); }}>{(products.data?.content ?? []).filter((product) => product.capabilities.includes('FOOD_SERVICE')).map((product) => <MenuItem key={product.id} value={product.id}>{product.name}</MenuItem>)}</TextField> : null}
        <TextField select label="Restaurant Category" value={item.categoryId} onChange={(event) => setItem({ ...item, categoryId: event.target.value })}>{(categories.data ?? []).map((value) => <MenuItem key={value.id} value={value.id}>{value.name}</MenuItem>)}</TextField>
        <TextField label="Name" value={item.displayName} onChange={(event) => setItem({ ...item, displayName: event.target.value })} />
        <TextField label="Description (optional)" multiline minRows={2} value={item.description} onChange={(event) => setItem({ ...item, description: event.target.value })} />
        <FormControlLabel control={<Switch checked={item.available} onChange={(_,available)=>setItem(current=>({...current,available}))}/>} label="Available" />
        <Typography fontWeight={800}>Pricing & display</Typography>
        <TextField label="Price" type="number" value={item.price} onChange={(event) => setItem({ ...item, price: Number(event.target.value) })} />
        <TextField label="Tile Position / Display Order" type="number" value={item.displayOrder} onChange={(event) => setItem({ ...item, displayOrder: Number(event.target.value) })} />
        <TextField label="Image URL (optional)" value={item.imageUrl} onChange={(event) => setItem({ ...item, imageUrl: event.target.value })} />
        <Typography fontWeight={800}>Variants</Typography>
        {item.variants.map(variant=><Stack key={variant.clientId} data-testid={`variant-row-${variant.clientId}`} direction={{xs:'column',sm:'row'}} spacing={1}>
          <TextField label="Variant name" value={variant.name} onChange={event=>setItem(current=>({...current,variants:current.variants.map(value=>value.clientId===variant.clientId?{...value,name:event.target.value}:value)}))}/>
          <TextField label="Variant price" type="number" value={variant.price} onChange={event=>setItem(current=>({...current,variants:current.variants.map(value=>value.clientId===variant.clientId?{...value,price:Number(event.target.value)}:value)}))}/>
          <FormControlLabel control={<Switch checked={variant.available} onChange={(_,available)=>setItem(current=>({...current,variants:current.variants.map(value=>value.clientId===variant.clientId?{...value,available}:value)}))}/>} label="Available" />
          <Button color="error" onClick={()=>setItem(current=>({...current,variants:current.variants.filter(value=>value.clientId!==variant.clientId)}))}>Remove Variant</Button>
        </Stack>)}
        <Button onClick={()=>setItem(current=>({...current,variants:[...current.variants,{clientId:newRowId('variant'),name:'',price:0,displayOrder:current.variants.length,available:true}]}))}>Add Variant</Button>
        <Typography fontWeight={800}>Included ingredients</Typography>
        {item.components.map(component=><Stack key={component.clientId} direction={{xs:'column',md:'row'}} spacing={1}><TextField label="Ingredient name" value={component.name} onChange={event=>setItem(current=>({...current,components:current.components.map(value=>value.clientId===component.clientId?{...value,name:event.target.value}:value)}))}/><FormControlLabel control={<Switch checked={component.removable} onChange={(_,checked)=>setItem(current=>({...current,components:current.components.map(value=>value.clientId===component.clientId?{...value,removable:checked}:value)}))}/>} label="Removable"/><FormControlLabel control={<Switch checked={component.allowExtra} onChange={(_,checked)=>setItem(current=>({...current,components:current.components.map(value=>value.clientId===component.clientId?{...value,allowExtra:checked,extraPrice:checked?value.extraPrice:0}:value)}))}/>} label="Allow extra"/>{component.allowExtra?<TextField label="Extra price" type="number" value={component.extraPrice} onChange={event=>setItem(current=>({...current,components:current.components.map(value=>value.clientId===component.clientId?{...value,extraPrice:Number(event.target.value)}:value)}))}/>:null}<Button color="error" onClick={()=>setItem(current=>({...current,components:current.components.filter(value=>value.clientId!==component.clientId)}))}>Remove</Button></Stack>)}
        <Button onClick={()=>setItem(current=>({...current,components:[...current.components,{clientId:newRowId('new-component'),name:'',includedByDefault:true,removable:true,allowExtra:false,extraPrice:0,displayOrder:current.components.length,active:true}]}))}>Add Ingredient</Button>
        <Typography fontWeight={800}>Choices & customizations</Typography>
        <TextField select label="Attach Choice Group" value="" onChange={event=>{const group=choiceGroups.data?.find(value=>value.id===event.target.value);if(group&&!item.modifierGroupAssignments.some(value=>value.modifierGroupId===group.id))setItem(current=>({...current,modifierGroupAssignments:[...current.modifierGroupAssignments,{modifierGroupId:group.id,minimumSelections:0,maximumSelections:1,displayOrder:current.modifierGroupAssignments.length,active:true}]}));}}>{(choiceGroups.data??[]).filter(group=>group.active&&!item.modifierGroupAssignments.some(value=>value.modifierGroupId===group.id)).map(group=><MenuItem key={group.id} value={group.id}>{group.name}</MenuItem>)}</TextField>
        <Button onClick={()=>{setAttachCreatedChoice(true);setEditingChoice(null);setChoiceOpen(true);}}>Create New Choice Group</Button>
        {item.modifierGroupAssignments.map(assignment=><AssignmentRules key={assignment.modifierGroupId} assignment={assignment} name={choiceGroups.data?.find(value=>value.id===assignment.modifierGroupId)?.name??'Choice Group'} optionCount={choiceGroups.data?.find(value=>value.id===assignment.modifierGroupId)?.options.length??1} update={next=>setItem(current=>({...current,modifierGroupAssignments:current.modifierGroupAssignments.map(value=>value.modifierGroupId===next.modifierGroupId?next:value)}))} remove={()=>setItem(current=>({...current,modifierGroupAssignments:current.modifierGroupAssignments.filter(value=>value.modifierGroupId!==assignment.modifierGroupId)}))}/>) }
      </Stack></DialogContent>
      <DialogActions><Button disabled={saveItem.isPending} onClick={() => setItemOpen(false)}>Cancel</Button><Button variant="contained" onClick={() => saveItem.mutate()} disabled={saveItem.isPending || !item.categoryId || !item.displayName.trim() || item.price<0 || item.variants.some(value=>!value.name.trim()||value.price<0) || item.components.some(value=>!value.name.trim()||value.extraPrice<0) || (linkProduct && !item.productId)}>{saveItem.isPending ? 'Saving…' : editingItemId ? 'Save Changes' : 'Add'}</Button></DialogActions>
    </Dialog>
    <ChoiceGroupDialog open={choiceOpen} initial={editingChoice} onClose={()=>setChoiceOpen(false)} save={async payload=>{const token=await getValidAccessToken();const saved=editingChoice?await updateFoodMenuChoiceGroup(token,selected,editingChoice.id,payload):await createFoodMenuChoiceGroup(token,selected,payload);if(attachCreatedChoice&&!editingChoice)setItem(current=>({...current,modifierGroupAssignments:[...current.modifierGroupAssignments,{modifierGroupId:saved.id,minimumSelections:0,maximumSelections:1,displayOrder:current.modifierGroupAssignments.length,active:true}]}));setChoiceOpen(false);setAttachCreatedChoice(false);refresh();}}/>
  </Stack>;
}

function newRowId(prefix: string) {
  return `${prefix}-${globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`}`;
}

type AssignmentDraft={modifierGroupId:string;minimumSelections:number;maximumSelections:number;displayOrder:number;active:boolean};
function AssignmentRules({assignment,name,optionCount,update,remove}:{assignment:AssignmentDraft;name:string;optionCount:number;update:(value:AssignmentDraft)=>void;remove:()=>void}){return <Card variant="outlined"><CardContent><Stack direction={{xs:'column',sm:'row'}} spacing={1} alignItems={{sm:'center'}}><Box sx={{flex:1}}><Typography fontWeight={700}>{name}</Typography><Typography variant="caption" color="text.secondary">{assignment.minimumSelections>0?'Required':'Optional'} · {assignment.minimumSelections===assignment.maximumSelections?`Choose ${assignment.maximumSelections}`:`Choose ${assignment.minimumSelections}–${assignment.maximumSelections}`}</Typography></Box><FormControlLabel control={<Switch checked={assignment.minimumSelections>0} onChange={(_,required)=>update({...assignment,minimumSelections:required?1:0,maximumSelections:Math.max(assignment.maximumSelections,1)})}/>} label="Required"/><TextField label="Min" type="number" value={assignment.minimumSelections} inputProps={{min:0,max:optionCount}} onChange={event=>update({...assignment,minimumSelections:Number(event.target.value)})} sx={{width:82}}/><TextField label="Max" type="number" value={assignment.maximumSelections} inputProps={{min:1,max:optionCount}} onChange={event=>update({...assignment,maximumSelections:Number(event.target.value)})} sx={{width:82}}/><TextField label="Order" type="number" value={assignment.displayOrder} inputProps={{min:0}} onChange={event=>update({...assignment,displayOrder:Number(event.target.value)})} sx={{width:88}}/><Button color="error" onClick={remove}>Detach</Button></Stack></CardContent></Card>}

function ChoiceGroupDialog({open,initial,onClose,save}:{open:boolean;initial:FoodMenuChoiceGroup|null;onClose:()=>void;save:(payload:{name:string;active:boolean;options:Array<{name:string;priceAdjustment:number;displayOrder:number;available:boolean}>})=>Promise<void>}){const [name,setName]=React.useState('');const [active,setActive]=React.useState(true);const [options,setOptions]=React.useState<Array<{clientId:string;persisted:boolean;name:string;priceAdjustment:number;displayOrder:number;available:boolean}>>([]);React.useEffect(()=>{if(open){setName(initial?.name??'');setActive(initial?.active??true);setOptions((initial?.options??[]).map(option=>({clientId:option.id,persisted:true,...option})));}},[open,initial]);return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{initial?'Edit':'Create'} Choice Group</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField label="Name" value={name} onChange={event=>setName(event.target.value)}/><FormControlLabel control={<Switch checked={active} onChange={(_,checked)=>setActive(checked)}/>} label="Active for new orders"/>{initial?.usageCount?<Alert severity="info">Used by {initial.usageCount} menu items{initial.usedBy.length?`: ${initial.usedBy.join(', ')}`:''}. Changes apply to new orders only.</Alert>:null}<Typography fontWeight={800}>Choices</Typography>{options.map(option=><Stack key={option.clientId} direction="row" spacing={1}><TextField label="Choice" value={option.name} onChange={event=>setOptions(values=>values.map(value=>value.clientId===option.clientId?{...value,name:event.target.value}:value))}/><TextField label="Added price" type="number" value={option.priceAdjustment} onChange={event=>setOptions(values=>values.map(value=>value.clientId===option.clientId?{...value,priceAdjustment:Number(event.target.value)}:value))}/><FormControlLabel control={<Switch checked={option.available} onChange={(_,checked)=>setOptions(values=>values.map(value=>value.clientId===option.clientId?{...value,available:checked}:value))}/>} label="Available"/>{option.persisted?null:<Button color="error" onClick={()=>setOptions(values=>values.filter(value=>value.clientId!==option.clientId))}>Remove</Button>}</Stack>)}<Button onClick={()=>setOptions(values=>[...values,{clientId:newRowId('choice'),persisted:false,name:'',priceAdjustment:0,displayOrder:values.length,available:true}])}>Add Choice</Button></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" disabled={!name.trim()||!options.length||options.some(option=>!option.name.trim()||option.priceAdjustment<0)} onClick={()=>void save({name,active,options:options.map(({clientId:_,persisted:__,...option})=>option)})}>Save Choice Group</Button></DialogActions></Dialog>}
