import AddIcon from '@mui/icons-material/Add';
import { Alert, Box, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, Grid, MenuItem, Stack, Switch, TextField, Typography } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import * as React from 'react';
import { createFoodMenuCategory, createFoodMenuItem, deleteFoodMenuCategory, deleteFoodMenuItem, listFoodMenuCategories, listFoodMenuItems, listProducts, listStores, updateFoodMenuCategory, updateFoodMenuItem, updateFoodMenuItemAvailability } from '../../api/client';
import type { FoodMenuItem } from '../../api/types';
import { useSession } from '../../app/session';

const emptyItem = { productId: '', categoryId: '', displayName: '', description: '', price: 0, displayOrder: 0, available: true, imageUrl: '' };

export function FoodMenuPage() {
  const { currentUser, getValidAccessToken } = useSession();
  const queryClient = useQueryClient();
  const stores = useQuery({ queryKey: ['stores', 'restaurant-menu'], queryFn: async () => listStores(await getValidAccessToken(), { size: 100 }) });
  const eligible = (stores.data?.content ?? []).filter((store) => store.capabilities?.includes('FOOD_SERVICE'));
  const [storeId, setStoreId] = React.useState('');
  const selected = storeId || eligible[0]?.id || '';
  const categories = useQuery({ queryKey: ['food-menu-categories', selected], queryFn: async () => listFoodMenuCategories(await getValidAccessToken(), selected), enabled: Boolean(selected) });
  const items = useQuery({ queryKey: ['food-menu-items', selected], queryFn: async () => listFoodMenuItems(await getValidAccessToken(), selected), enabled: Boolean(selected) });
  const products = useQuery({ queryKey: ['products', 'restaurant-menu', selected], queryFn: async () => listProducts(await getValidAccessToken(), { storeId: selected, active: true, size: 200 }), enabled: Boolean(selected) });
  const [categoryOpen, setCategoryOpen] = React.useState(false);
  const [itemOpen, setItemOpen] = React.useState(false);
  const [linkProduct, setLinkProduct] = React.useState(false);
  const [category, setCategory] = React.useState({ name: '', displayOrder: 0, active: true, imageUrl: '' });
  const [item, setItem] = React.useState(emptyItem);
  const canManage = currentUser?.permissions?.some((permission) => permission === 'PRODUCT_MANAGE' || permission === 'FOOD_ORDER_UPDATE');
  const refresh = () => {
    void queryClient.invalidateQueries({ queryKey: ['food-menu-categories', selected] });
    void queryClient.invalidateQueries({ queryKey: ['food-menu-items', selected] });
  };
  const addCategory = useMutation({ mutationFn: async () => createFoodMenuCategory(await getValidAccessToken(), selected, category), onSuccess: () => { setCategoryOpen(false); setCategory({ name: '', displayOrder: 0, active: true, imageUrl: '' }); refresh(); } });
  const addItem = useMutation({ mutationFn: async () => createFoodMenuItem(await getValidAccessToken(), selected, { ...item, productId: linkProduct ? item.productId : undefined }), onSuccess: () => { setItemOpen(false); setItem(emptyItem); setLinkProduct(false); refresh(); } });
  const availability = useMutation({ mutationFn: async (value: { id: string; available: boolean }) => updateFoodMenuItemAvailability(await getValidAccessToken(), selected, value.id, value.available), onSuccess: refresh });
  const changeCategory = useMutation({ mutationFn: async (value: { id: string; name: string; displayOrder: number; active: boolean; imageUrl?: string }) => updateFoodMenuCategory(await getValidAccessToken(), selected, value.id, value), onSuccess: refresh });
  const moveItem = useMutation({ mutationFn: async (value: FoodMenuItem) => updateFoodMenuItem(await getValidAccessToken(), selected, value.id, { productId: value.productId ?? undefined, categoryId: value.categoryId, displayName: value.displayName, description: value.description ?? undefined, price: value.price, displayOrder: value.displayOrder, available: value.available, imageUrl: value.imageUrl ?? undefined }), onSuccess: refresh });
  const removeCategory = useMutation({ mutationFn: async (id: string) => deleteFoodMenuCategory(await getValidAccessToken(), selected, id), onSuccess: refresh });
  const removeItem = useMutation({ mutationFn: async (id: string) => deleteFoodMenuItem(await getValidAccessToken(), selected, id), onSuccess: refresh });

  if (stores.isSuccess && !eligible.length) return <Alert severity="info">No FOOD_SERVICE-enabled stores are available.</Alert>;
  return <Stack spacing={3} sx={{ minWidth: 0 }}>
    <Box><Typography variant="h4">Restaurant Menu</Typography><Typography color="text.secondary">Made-to-order items are separate from Retail Products and Inventory.</Typography></Box>
    <TextField select label="Store" value={selected} onChange={(event) => setStoreId(event.target.value)} sx={{ maxWidth: 420 }}>{eligible.map((store) => <MenuItem key={store.id} value={store.id}>{store.name}</MenuItem>)}</TextField>
    <Stack direction="row" spacing={1} useFlexGap flexWrap="wrap"><Button startIcon={<AddIcon />} variant="contained" disabled={!selected || !canManage} onClick={() => setCategoryOpen(true)}>Add Category</Button><Button startIcon={<AddIcon />} variant="contained" disabled={!selected || !categories.data?.length || !canManage} onClick={() => setItemOpen(true)}>Add Menu Item</Button></Stack>
    {categories.isSuccess && !categories.data.length ? <Alert severity="info" action={canManage ? <Button onClick={() => setCategoryOpen(true)}>Create Restaurant Menu</Button> : undefined}>No restaurant menu has been created for this store yet.</Alert> : null}
    {(categories.data ?? []).map((group) => <Box key={group.id} sx={{ minWidth: 0 }}>
      <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1} sx={{ mb: 1 }}><Typography variant="h5" sx={{ flex: 1 }}>{group.name} <Typography component="span" color="text.secondary">#{group.displayOrder}{group.active ? '' : ' · Inactive'}</Typography></Typography><Stack direction="row" useFlexGap flexWrap="wrap"><Button size="small" disabled={!canManage} onClick={() => changeCategory.mutate({ ...group, displayOrder: Math.max(0, group.displayOrder - 1), imageUrl: group.imageUrl ?? undefined })}>Move Up</Button><Button size="small" disabled={!canManage} onClick={() => changeCategory.mutate({ ...group, displayOrder: group.displayOrder + 1, imageUrl: group.imageUrl ?? undefined })}>Move Down</Button><Button size="small" disabled={!canManage} onClick={() => changeCategory.mutate({ ...group, active: !group.active, imageUrl: group.imageUrl ?? undefined })}>{group.active ? 'Deactivate' : 'Activate'}</Button><Button size="small" color="error" disabled={!canManage} onClick={() => removeCategory.mutate(group.id)}>Delete</Button></Stack></Stack>
      <Grid container spacing={2}>{(items.data ?? []).filter((value) => value.categoryId === group.id).map((value) => <Grid item xs={12} sm={6} md={4} key={value.id}><Card variant="outlined"><CardContent><Stack spacing={1}><Typography variant="h6">{value.displayName}</Typography>{value.description ? <Typography variant="body2">{value.description}</Typography> : null}<Typography>${Number(value.price).toFixed(2)} · position {value.displayOrder}</Typography><Typography variant="caption">{value.madeToOrder ? 'Made to Order · No inventory tracking' : `Linked Product: ${value.productName}`}</Typography><FormControlLabel control={<Switch checked={value.available} disabled={!canManage || availability.isPending} onChange={(_, checked) => availability.mutate({ id: value.id, available: checked })} />} label={value.available ? 'Available' : 'Sold Out'} /><Stack direction="row" useFlexGap flexWrap="wrap"><Button size="small" disabled={!canManage} onClick={() => moveItem.mutate({ ...value, displayOrder: Math.max(0, value.displayOrder - 1) })}>Move Up</Button><Button size="small" disabled={!canManage} onClick={() => moveItem.mutate({ ...value, displayOrder: value.displayOrder + 1 })}>Move Down</Button><Button size="small" color="error" disabled={!canManage} onClick={() => removeItem.mutate(value.id)}>Remove</Button></Stack></Stack></CardContent></Card></Grid>)}</Grid>
    </Box>)}
    <Dialog open={categoryOpen} onClose={() => setCategoryOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Create Restaurant Menu Category</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Name" value={category.name} onChange={(event) => setCategory({ ...category, name: event.target.value })} /><TextField label="Display Order" type="number" value={category.displayOrder} onChange={(event) => setCategory({ ...category, displayOrder: Number(event.target.value) })} /></Stack></DialogContent><DialogActions><Button onClick={() => setCategoryOpen(false)}>Cancel</Button><Button onClick={() => addCategory.mutate()} disabled={!category.name.trim()}>Add</Button></DialogActions></Dialog>
    <Dialog open={itemOpen} onClose={() => setItemOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Add Restaurant Menu Item</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><FormControlLabel control={<Switch checked={!linkProduct} onChange={(_, madeToOrder) => setLinkProduct(!madeToOrder)} />} label="Made to Order / No Inventory Tracking" />{linkProduct ? <TextField select label="Link Existing Product" value={item.productId} onChange={(event) => { const product = products.data?.content.find((candidate) => candidate.id === event.target.value); setItem({ ...item, productId: event.target.value, displayName: product?.name ?? '', price: product?.price ?? 0 }); }}>{(products.data?.content ?? []).filter((product) => product.capabilities.includes('FOOD_SERVICE')).map((product) => <MenuItem key={product.id} value={product.id}>{product.name}</MenuItem>)}</TextField> : null}<TextField select label="Restaurant Category" value={item.categoryId} onChange={(event) => setItem({ ...item, categoryId: event.target.value })}>{(categories.data ?? []).map((value) => <MenuItem key={value.id} value={value.id}>{value.name}</MenuItem>)}</TextField><TextField label="Name" value={item.displayName} onChange={(event) => setItem({ ...item, displayName: event.target.value })} /><TextField label="Description (optional)" multiline minRows={2} value={item.description} onChange={(event) => setItem({ ...item, description: event.target.value })} /><TextField label="Price" type="number" value={item.price} onChange={(event) => setItem({ ...item, price: Number(event.target.value) })} /><TextField label="Tile Position / Display Order" type="number" value={item.displayOrder} onChange={(event) => setItem({ ...item, displayOrder: Number(event.target.value) })} /><TextField label="Image URL (optional)" value={item.imageUrl} onChange={(event) => setItem({ ...item, imageUrl: event.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={() => setItemOpen(false)}>Cancel</Button><Button onClick={() => addItem.mutate()} disabled={!item.categoryId || !item.displayName.trim() || (linkProduct && !item.productId)}>Add</Button></DialogActions></Dialog>
  </Stack>;
}
