package com.merchtyl.lottery;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

public record LotterySettlementResponse(
        UUID id,
        UUID operatorId,
        String operatorCode,
        String operatorName,
        UUID jurisdictionId,
        String jurisdictionCode,
        String jurisdictionName,
        UUID storeId,
        String storeCode,
        String storeName,
        LocalDate periodStart,
        LocalDate periodEnd,
        BigDecimal grossSales,
        BigDecimal totalPayouts,
        BigDecimal cancellations,
        BigDecimal adjustments,
        BigDecimal commission,
        BigDecimal expectedSettlement,
        String currencyCode,
        Instant calculatedAt,
        LotterySettlementStatus status,
        UUID approvedBy,
        String approvedByEmail,
        String approvedByDisplayName,
        Instant approvedAt,
        UUID postedBy,
        String postedByEmail,
        String postedByDisplayName,
        Instant postedAt,
        UUID reopenedBy,
        String reopenedByEmail,
        String reopenedByDisplayName,
        Instant reopenedAt,
        String reopenReason,
        String lifecycleNotes,
        Instant createdAt,
        Instant updatedAt,
        long version
) {
    public static LotterySettlementResponse from(LotterySettlement settlement) {
        return new LotterySettlementResponse(
                settlement.getId(),
                settlement.getOperator().getId(),
                settlement.getOperator().getCode(),
                settlement.getOperator().getName(),
                settlement.getJurisdiction().getId(),
                settlement.getJurisdiction().getCode(),
                settlement.getJurisdiction().getName(),
                settlement.getStore().getId(),
                settlement.getStore().getCode(),
                settlement.getStore().getName(),
                settlement.getPeriodStart(),
                settlement.getPeriodEnd(),
                settlement.getGrossSales(),
                settlement.getTotalPayouts(),
                settlement.getCancellations(),
                settlement.getAdjustments(),
                settlement.getCommission(),
                settlement.getExpectedSettlement(),
                settlement.getCurrencyCode(),
                settlement.getCalculatedAt(),
                settlement.getStatus(),
                settlement.getApprovedBy() == null ? null : settlement.getApprovedBy().getId(),
                settlement.getApprovedBy() == null ? null : settlement.getApprovedBy().getEmail(),
                settlement.getApprovedBy() == null ? null : settlement.getApprovedBy().getDisplayName(),
                settlement.getApprovedAt(),
                settlement.getPostedBy() == null ? null : settlement.getPostedBy().getId(),
                settlement.getPostedBy() == null ? null : settlement.getPostedBy().getEmail(),
                settlement.getPostedBy() == null ? null : settlement.getPostedBy().getDisplayName(),
                settlement.getPostedAt(),
                settlement.getReopenedBy() == null ? null : settlement.getReopenedBy().getId(),
                settlement.getReopenedBy() == null ? null : settlement.getReopenedBy().getEmail(),
                settlement.getReopenedBy() == null ? null : settlement.getReopenedBy().getDisplayName(),
                settlement.getReopenedAt(),
                settlement.getReopenReason(),
                settlement.getLifecycleNotes(),
                settlement.getCreatedAt(),
                settlement.getUpdatedAt(),
                settlement.getVersion());
    }
}
