package com.merchtyl.lottery;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

public record LotteryPayoutResponse(
        UUID id,
        UUID operatorId,
        String operatorCode,
        String operatorName,
        UUID policyId,
        UUID storeId,
        String storeCode,
        String storeName,
        UUID registerId,
        String registerCode,
        String registerName,
        UUID deviceId,
        String deviceIdentifier,
        String deviceDisplayName,
        UUID cashierId,
        String cashierEmail,
        String cashierDisplayName,
        UUID registerSessionId,
        String ticketNumber,
        String validationReference,
        BigDecimal amount,
        String currencyCode,
        LotteryPayoutMethod payoutMethod,
        LotteryPayoutStatus status,
        LotteryVerificationState ticketValidationState,
        LotteryVerificationState ageVerificationState,
        LotteryVerificationState identificationVerificationState,
        BigDecimal cashierApprovalLimit,
        BigDecimal managerApprovalThreshold,
        BigDecimal operatorReferralThreshold,
        BigDecimal maximumCashPayout,
        boolean ticketValidationRequired,
        boolean ageVerificationRequired,
        boolean identificationRequired,
        boolean alternateRegisterAllowed,
        LocalDate businessDate,
        Instant occurredAt,
        UUID validatedBy,
        Instant validatedAt,
        UUID authorizedBy,
        Instant authorizedAt,
        UUID paidBy,
        Instant paidAt,
        UUID rejectedBy,
        Instant rejectedAt,
        String rejectionReason,
        String notes,
        List<LotteryPayoutApprovalResponse> approvals,
        Instant createdAt,
        Instant updatedAt,
        long version
) {
    public static LotteryPayoutResponse from(LotteryPayout payout) {
        return new LotteryPayoutResponse(
                payout.getId(),
                payout.getOperator().getId(),
                payout.getOperator().getCode(),
                payout.getOperator().getName(),
                payout.getPolicy().getId(),
                payout.getStore().getId(),
                payout.getStore().getCode(),
                payout.getStore().getName(),
                payout.getRegister().getId(),
                payout.getRegister().getCode(),
                payout.getRegister().getName(),
                payout.getDevice().getId(),
                payout.getDevice().getDeviceIdentifier(),
                payout.getDevice().getDisplayName(),
                payout.getCashier().getId(),
                payout.getCashier().getEmail(),
                payout.getCashier().getDisplayName(),
                payout.getRegisterSession() == null ? null : payout.getRegisterSession().getId(),
                payout.getTicketNumber(),
                payout.getValidationReference(),
                payout.getAmount(),
                payout.getCurrencyCode(),
                payout.getPayoutMethod(),
                payout.getStatus(),
                payout.getTicketValidationState(),
                payout.getAgeVerificationState(),
                payout.getIdentificationVerificationState(),
                payout.getCashierApprovalLimit(),
                payout.getManagerApprovalThreshold(),
                payout.getOperatorReferralThreshold(),
                payout.getMaximumCashPayout(),
                payout.isTicketValidationRequired(),
                payout.isAgeVerificationRequired(),
                payout.isIdentificationRequired(),
                payout.isAlternateRegisterAllowed(),
                payout.getBusinessDate(),
                payout.getOccurredAt(),
                payout.getValidatedBy() == null ? null : payout.getValidatedBy().getId(),
                payout.getValidatedAt(),
                payout.getAuthorizedBy() == null ? null : payout.getAuthorizedBy().getId(),
                payout.getAuthorizedAt(),
                payout.getPaidBy() == null ? null : payout.getPaidBy().getId(),
                payout.getPaidAt(),
                payout.getRejectedBy() == null ? null : payout.getRejectedBy().getId(),
                payout.getRejectedAt(),
                payout.getRejectionReason(),
                payout.getNotes(),
                payout.getApprovals().stream().map(LotteryPayoutApprovalResponse::from).toList(),
                payout.getCreatedAt(),
                payout.getUpdatedAt(),
                payout.getVersion());
    }
}
